/*
 * Copyright (c) 2005 Henri Sivonen
 * Copyright (c) 2008-2010 Mozilla Foundation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a 
 * copy of this software and associated documentation files (the "Software"), 
 * to deal in the Software without restriction, including without limitation 
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the 
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in 
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
 * DEALINGS IN THE SOFTWARE.
 */

package nu.validator.htmlparser.impl;

import nu.validator.htmlparser.annotation.NoLength;

/**
 * @version $Id$
 * @author hsivonen
 */
public final class NamedCharacters {

    /**
     * This method is necessary to work out the 2^16 byte limit of the static
     * initializer.
     * 
     * @param str
     * @return
     */
    private static byte[] toByteArray(String str) {
        byte[] arr = new byte[str.length()];
        for (int i = 0; i < str.length(); i++) {
            arr[i] = (byte) str.charAt(i);
        }
        return arr;
    }

    static final @NoLength byte[][] NAMES = { toByteArray("lig"),
            toByteArray("lig;"), toByteArray("P"), toByteArray("P;"),
            toByteArray("cute"), toByteArray("cute;"), toByteArray("reve;"),
            toByteArray("irc"), toByteArray("irc;"), toByteArray("y;"),
            toByteArray("r;"), toByteArray("rave"), toByteArray("rave;"),
            toByteArray("pha;"), toByteArray("acr;"), toByteArray("d;"),
            toByteArray("gon;"), toByteArray("pf;"),
            toByteArray("plyFunction;"), toByteArray("ing"),
            toByteArray("ing;"), toByteArray("cr;"), toByteArray("sign;"),
            toByteArray("ilde"), toByteArray("ilde;"), toByteArray("ml"),
            toByteArray("ml;"), toByteArray("ckslash;"), toByteArray("rv;"),
            toByteArray("rwed;"), toByteArray("y;"), toByteArray("cause;"),
            toByteArray("rnoullis;"), toByteArray("ta;"), toByteArray("r;"),
            toByteArray("pf;"), toByteArray("eve;"), toByteArray("cr;"),
            toByteArray("mpeq;"), toByteArray("cy;"), toByteArray("PY"),
            toByteArray("PY;"), toByteArray("cute;"), toByteArray("p;"),
            toByteArray("pitalDifferentialD;"), toByteArray("yleys;"),
            toByteArray("aron;"), toByteArray("edil"), toByteArray("edil;"),
            toByteArray("irc;"), toByteArray("onint;"), toByteArray("ot;"),
            toByteArray("dilla;"), toByteArray("nterDot;"), toByteArray("r;"),
            toByteArray("i;"), toByteArray("rcleDot;"),
            toByteArray("rcleMinus;"), toByteArray("rclePlus;"),
            toByteArray("rcleTimes;"), toByteArray("ockwiseContourIntegral;"),
            toByteArray("oseCurlyDoubleQuote;"), toByteArray("oseCurlyQuote;"),
            toByteArray("lon;"), toByteArray("lone;"), toByteArray("ngruent;"),
            toByteArray("nint;"), toByteArray("ntourIntegral;"),
            toByteArray("pf;"), toByteArray("product;"),
            toByteArray("unterClockwiseContourIntegral;"), toByteArray("oss;"),
            toByteArray("cr;"), toByteArray("p;"), toByteArray("pCap;"),
            toByteArray(";"), toByteArray("otrahd;"), toByteArray("cy;"),
            toByteArray("cy;"), toByteArray("cy;"), toByteArray("gger;"),
            toByteArray("rr;"), toByteArray("shv;"), toByteArray("aron;"),
            toByteArray("y;"), toByteArray("l;"), toByteArray("lta;"),
            toByteArray("r;"), toByteArray("acriticalAcute;"),
            toByteArray("acriticalDot;"), toByteArray("acriticalDoubleAcute;"),
            toByteArray("acriticalGrave;"), toByteArray("acriticalTilde;"),
            toByteArray("amond;"), toByteArray("fferentialD;"),
            toByteArray("pf;"), toByteArray("t;"), toByteArray("tDot;"),
            toByteArray("tEqual;"), toByteArray("ubleContourIntegral;"),
            toByteArray("ubleDot;"), toByteArray("ubleDownArrow;"),
            toByteArray("ubleLeftArrow;"), toByteArray("ubleLeftRightArrow;"),
            toByteArray("ubleLeftTee;"), toByteArray("ubleLongLeftArrow;"),
            toByteArray("ubleLongLeftRightArrow;"),
            toByteArray("ubleLongRightArrow;"), toByteArray("ubleRightArrow;"),
            toByteArray("ubleRightTee;"), toByteArray("ubleUpArrow;"),
            toByteArray("ubleUpDownArrow;"), toByteArray("ubleVerticalBar;"),
            toByteArray("wnArrow;"), toByteArray("wnArrowBar;"),
            toByteArray("wnArrowUpArrow;"), toByteArray("wnBreve;"),
            toByteArray("wnLeftRightVector;"), toByteArray("wnLeftTeeVector;"),
            toByteArray("wnLeftVector;"), toByteArray("wnLeftVectorBar;"),
            toByteArray("wnRightTeeVector;"), toByteArray("wnRightVector;"),
            toByteArray("wnRightVectorBar;"), toByteArray("wnTee;"),
            toByteArray("wnTeeArrow;"), toByteArray("wnarrow;"),
            toByteArray("cr;"), toByteArray("trok;"), toByteArray("G;"),
            toByteArray("H"), toByteArray("H;"), toByteArray("cute"),
            toByteArray("cute;"), toByteArray("aron;"), toByteArray("irc"),
            toByteArray("irc;"), toByteArray("y;"), toByteArray("ot;"),
            toByteArray("r;"), toByteArray("rave"), toByteArray("rave;"),
            toByteArray("ement;"), toByteArray("acr;"),
            toByteArray("ptySmallSquare;"), toByteArray("ptyVerySmallSquare;"),
            toByteArray("gon;"), toByteArray("pf;"), toByteArray("silon;"),
            toByteArray("ual;"), toByteArray("ualTilde;"),
            toByteArray("uilibrium;"), toByteArray("cr;"), toByteArray("im;"),
            toByteArray("a;"), toByteArray("ml"), toByteArray("ml;"),
            toByteArray("ists;"), toByteArray("ponentialE;"),
            toByteArray("y;"), toByteArray("r;"),
            toByteArray("lledSmallSquare;"),
            toByteArray("lledVerySmallSquare;"), toByteArray("pf;"),
            toByteArray("rAll;"), toByteArray("uriertrf;"), toByteArray("cr;"),
            toByteArray("cy;"), toByteArray(""), toByteArray(";"),
            toByteArray("mma;"), toByteArray("mmad;"), toByteArray("reve;"),
            toByteArray("edil;"), toByteArray("irc;"), toByteArray("y;"),
            toByteArray("ot;"), toByteArray("r;"), toByteArray(";"),
            toByteArray("pf;"), toByteArray("eaterEqual;"),
            toByteArray("eaterEqualLess;"), toByteArray("eaterFullEqual;"),
            toByteArray("eaterGreater;"), toByteArray("eaterLess;"),
            toByteArray("eaterSlantEqual;"), toByteArray("eaterTilde;"),
            toByteArray("cr;"), toByteArray(";"), toByteArray("RDcy;"),
            toByteArray("cek;"), toByteArray("t;"), toByteArray("irc;"),
            toByteArray("r;"), toByteArray("lbertSpace;"), toByteArray("pf;"),
            toByteArray("rizontalLine;"), toByteArray("cr;"),
            toByteArray("trok;"), toByteArray("mpDownHump;"),
            toByteArray("mpEqual;"), toByteArray("cy;"), toByteArray("lig;"),
            toByteArray("cy;"), toByteArray("cute"), toByteArray("cute;"),
            toByteArray("irc"), toByteArray("irc;"), toByteArray("y;"),
            toByteArray("ot;"), toByteArray("r;"), toByteArray("rave"),
            toByteArray("rave;"), toByteArray(";"), toByteArray("acr;"),
            toByteArray("aginaryI;"), toByteArray("plies;"), toByteArray("t;"),
            toByteArray("tegral;"), toByteArray("tersection;"),
            toByteArray("visibleComma;"), toByteArray("visibleTimes;"),
            toByteArray("gon;"), toByteArray("pf;"), toByteArray("ta;"),
            toByteArray("cr;"), toByteArray("ilde;"), toByteArray("kcy;"),
            toByteArray("ml"), toByteArray("ml;"), toByteArray("irc;"),
            toByteArray("y;"), toByteArray("r;"), toByteArray("pf;"),
            toByteArray("cr;"), toByteArray("ercy;"), toByteArray("kcy;"),
            toByteArray("cy;"), toByteArray("cy;"), toByteArray("ppa;"),
            toByteArray("edil;"), toByteArray("y;"), toByteArray("r;"),
            toByteArray("pf;"), toByteArray("cr;"), toByteArray("cy;"),
            toByteArray(""), toByteArray(";"), toByteArray("cute;"),
            toByteArray("mbda;"), toByteArray("ng;"), toByteArray("placetrf;"),
            toByteArray("rr;"), toByteArray("aron;"), toByteArray("edil;"),
            toByteArray("y;"), toByteArray("ftAngleBracket;"),
            toByteArray("ftArrow;"), toByteArray("ftArrowBar;"),
            toByteArray("ftArrowRightArrow;"), toByteArray("ftCeiling;"),
            toByteArray("ftDoubleBracket;"), toByteArray("ftDownTeeVector;"),
            toByteArray("ftDownVector;"), toByteArray("ftDownVectorBar;"),
            toByteArray("ftFloor;"), toByteArray("ftRightArrow;"),
            toByteArray("ftRightVector;"), toByteArray("ftTee;"),
            toByteArray("ftTeeArrow;"), toByteArray("ftTeeVector;"),
            toByteArray("ftTriangle;"), toByteArray("ftTriangleBar;"),
            toByteArray("ftTriangleEqual;"), toByteArray("ftUpDownVector;"),
            toByteArray("ftUpTeeVector;"), toByteArray("ftUpVector;"),
            toByteArray("ftUpVectorBar;"), toByteArray("ftVector;"),
            toByteArray("ftVectorBar;"), toByteArray("ftarrow;"),
            toByteArray("ftrightarrow;"), toByteArray("ssEqualGreater;"),
            toByteArray("ssFullEqual;"), toByteArray("ssGreater;"),
            toByteArray("ssLess;"), toByteArray("ssSlantEqual;"),
            toByteArray("ssTilde;"), toByteArray("r;"), toByteArray(";"),
            toByteArray("eftarrow;"), toByteArray("idot;"),
            toByteArray("ngLeftArrow;"), toByteArray("ngLeftRightArrow;"),
            toByteArray("ngRightArrow;"), toByteArray("ngleftarrow;"),
            toByteArray("ngleftrightarrow;"), toByteArray("ngrightarrow;"),
            toByteArray("pf;"), toByteArray("werLeftArrow;"),
            toByteArray("werRightArrow;"), toByteArray("cr;"),
            toByteArray("h;"), toByteArray("trok;"), toByteArray(";"),
            toByteArray("p;"), toByteArray("y;"), toByteArray("diumSpace;"),
            toByteArray("llintrf;"), toByteArray("r;"),
            toByteArray("nusPlus;"), toByteArray("pf;"), toByteArray("cr;"),
            toByteArray(";"), toByteArray("cy;"), toByteArray("cute;"),
            toByteArray("aron;"), toByteArray("edil;"), toByteArray("y;"),
            toByteArray("gativeMediumSpace;"),
            toByteArray("gativeThickSpace;"), toByteArray("gativeThinSpace;"),
            toByteArray("gativeVeryThinSpace;"),
            toByteArray("stedGreaterGreater;"), toByteArray("stedLessLess;"),
            toByteArray("wLine;"), toByteArray("r;"), toByteArray("Break;"),
            toByteArray("nBreakingSpace;"), toByteArray("pf;"),
            toByteArray("t;"), toByteArray("tCongruent;"),
            toByteArray("tCupCap;"), toByteArray("tDoubleVerticalBar;"),
            toByteArray("tElement;"), toByteArray("tEqual;"),
            toByteArray("tExists;"), toByteArray("tGreater;"),
            toByteArray("tGreaterEqual;"), toByteArray("tGreaterLess;"),
            toByteArray("tGreaterTilde;"), toByteArray("tLeftTriangle;"),
            toByteArray("tLeftTriangleEqual;"), toByteArray("tLess;"),
            toByteArray("tLessEqual;"), toByteArray("tLessGreater;"),
            toByteArray("tLessTilde;"), toByteArray("tPrecedes;"),
            toByteArray("tPrecedesSlantEqual;"),
            toByteArray("tReverseElement;"), toByteArray("tRightTriangle;"),
            toByteArray("tRightTriangleEqual;"),
            toByteArray("tSquareSubsetEqual;"),
            toByteArray("tSquareSupersetEqual;"), toByteArray("tSubsetEqual;"),
            toByteArray("tSucceeds;"), toByteArray("tSucceedsSlantEqual;"),
            toByteArray("tSupersetEqual;"), toByteArray("tTilde;"),
            toByteArray("tTildeEqual;"), toByteArray("tTildeFullEqual;"),
            toByteArray("tTildeTilde;"), toByteArray("tVerticalBar;"),
            toByteArray("cr;"), toByteArray("ilde"), toByteArray("ilde;"),
            toByteArray(";"), toByteArray("lig;"), toByteArray("cute"),
            toByteArray("cute;"), toByteArray("irc"), toByteArray("irc;"),
            toByteArray("y;"), toByteArray("blac;"), toByteArray("r;"),
            toByteArray("rave"), toByteArray("rave;"), toByteArray("acr;"),
            toByteArray("ega;"), toByteArray("icron;"), toByteArray("pf;"),
            toByteArray("enCurlyDoubleQuote;"), toByteArray("enCurlyQuote;"),
            toByteArray(";"), toByteArray("cr;"), toByteArray("lash"),
            toByteArray("lash;"), toByteArray("ilde"), toByteArray("ilde;"),
            toByteArray("imes;"), toByteArray("ml"), toByteArray("ml;"),
            toByteArray("erBar;"), toByteArray("erBrace;"),
            toByteArray("erBracket;"), toByteArray("erParenthesis;"),
            toByteArray("rtialD;"), toByteArray("y;"), toByteArray("r;"),
            toByteArray("i;"), toByteArray(";"), toByteArray("usMinus;"),
            toByteArray("incareplane;"), toByteArray("pf;"), toByteArray(";"),
            toByteArray("ecedes;"), toByteArray("ecedesEqual;"),
            toByteArray("ecedesSlantEqual;"), toByteArray("ecedesTilde;"),
            toByteArray("ime;"), toByteArray("oduct;"),
            toByteArray("oportion;"), toByteArray("oportional;"),
            toByteArray("cr;"), toByteArray("i;"), toByteArray("OT"),
            toByteArray("OT;"), toByteArray("r;"), toByteArray("pf;"),
            toByteArray("cr;"), toByteArray("arr;"), toByteArray("G"),
            toByteArray("G;"), toByteArray("cute;"), toByteArray("ng;"),
            toByteArray("rr;"), toByteArray("rrtl;"), toByteArray("aron;"),
            toByteArray("edil;"), toByteArray("y;"), toByteArray(";"),
            toByteArray("verseElement;"), toByteArray("verseEquilibrium;"),
            toByteArray("verseUpEquilibrium;"), toByteArray("r;"),
            toByteArray("o;"), toByteArray("ghtAngleBracket;"),
            toByteArray("ghtArrow;"), toByteArray("ghtArrowBar;"),
            toByteArray("ghtArrowLeftArrow;"), toByteArray("ghtCeiling;"),
            toByteArray("ghtDoubleBracket;"), toByteArray("ghtDownTeeVector;"),
            toByteArray("ghtDownVector;"), toByteArray("ghtDownVectorBar;"),
            toByteArray("ghtFloor;"), toByteArray("ghtTee;"),
            toByteArray("ghtTeeArrow;"), toByteArray("ghtTeeVector;"),
            toByteArray("ghtTriangle;"), toByteArray("ghtTriangleBar;"),
            toByteArray("ghtTriangleEqual;"), toByteArray("ghtUpDownVector;"),
            toByteArray("ghtUpTeeVector;"), toByteArray("ghtUpVector;"),
            toByteArray("ghtUpVectorBar;"), toByteArray("ghtVector;"),
            toByteArray("ghtVectorBar;"), toByteArray("ghtarrow;"),
            toByteArray("pf;"), toByteArray("undImplies;"),
            toByteArray("ightarrow;"), toByteArray("cr;"), toByteArray("h;"),
            toByteArray("leDelayed;"), toByteArray("CHcy;"),
            toByteArray("cy;"), toByteArray("FTcy;"), toByteArray("cute;"),
            toByteArray(";"), toByteArray("aron;"), toByteArray("edil;"),
            toByteArray("irc;"), toByteArray("y;"), toByteArray("r;"),
            toByteArray("ortDownArrow;"), toByteArray("ortLeftArrow;"),
            toByteArray("ortRightArrow;"), toByteArray("ortUpArrow;"),
            toByteArray("gma;"), toByteArray("allCircle;"), toByteArray("pf;"),
            toByteArray("rt;"), toByteArray("uare;"),
            toByteArray("uareIntersection;"), toByteArray("uareSubset;"),
            toByteArray("uareSubsetEqual;"), toByteArray("uareSuperset;"),
            toByteArray("uareSupersetEqual;"), toByteArray("uareUnion;"),
            toByteArray("cr;"), toByteArray("ar;"), toByteArray("b;"),
            toByteArray("bset;"), toByteArray("bsetEqual;"),
            toByteArray("cceeds;"), toByteArray("cceedsEqual;"),
            toByteArray("cceedsSlantEqual;"), toByteArray("cceedsTilde;"),
            toByteArray("chThat;"), toByteArray("m;"), toByteArray("p;"),
            toByteArray("perset;"), toByteArray("persetEqual;"),
            toByteArray("pset;"), toByteArray("ORN"), toByteArray("ORN;"),
            toByteArray("ADE;"), toByteArray("Hcy;"), toByteArray("cy;"),
            toByteArray("b;"), toByteArray("u;"), toByteArray("aron;"),
            toByteArray("edil;"), toByteArray("y;"), toByteArray("r;"),
            toByteArray("erefore;"), toByteArray("eta;"),
            toByteArray("inSpace;"), toByteArray("lde;"),
            toByteArray("ldeEqual;"), toByteArray("ldeFullEqual;"),
            toByteArray("ldeTilde;"), toByteArray("pf;"),
            toByteArray("ipleDot;"), toByteArray("cr;"), toByteArray("trok;"),
            toByteArray("cute"), toByteArray("cute;"), toByteArray("rr;"),
            toByteArray("rrocir;"), toByteArray("rcy;"), toByteArray("reve;"),
            toByteArray("irc"), toByteArray("irc;"), toByteArray("y;"),
            toByteArray("blac;"), toByteArray("r;"), toByteArray("rave"),
            toByteArray("rave;"), toByteArray("acr;"), toByteArray("derBar;"),
            toByteArray("derBrace;"), toByteArray("derBracket;"),
            toByteArray("derParenthesis;"), toByteArray("ion;"),
            toByteArray("ionPlus;"), toByteArray("gon;"), toByteArray("pf;"),
            toByteArray("Arrow;"), toByteArray("ArrowBar;"),
            toByteArray("ArrowDownArrow;"), toByteArray("DownArrow;"),
            toByteArray("Equilibrium;"), toByteArray("Tee;"),
            toByteArray("TeeArrow;"), toByteArray("arrow;"),
            toByteArray("downarrow;"), toByteArray("perLeftArrow;"),
            toByteArray("perRightArrow;"), toByteArray("si;"),
            toByteArray("silon;"), toByteArray("ing;"), toByteArray("cr;"),
            toByteArray("ilde;"), toByteArray("ml"), toByteArray("ml;"),
            toByteArray("ash;"), toByteArray("ar;"), toByteArray("y;"),
            toByteArray("ash;"), toByteArray("ashl;"), toByteArray("e;"),
            toByteArray("rbar;"), toByteArray("rt;"),
            toByteArray("rticalBar;"), toByteArray("rticalLine;"),
            toByteArray("rticalSeparator;"), toByteArray("rticalTilde;"),
            toByteArray("ryThinSpace;"), toByteArray("r;"), toByteArray("pf;"),
            toByteArray("cr;"), toByteArray("dash;"), toByteArray("irc;"),
            toByteArray("dge;"), toByteArray("r;"), toByteArray("pf;"),
            toByteArray("cr;"), toByteArray("r;"), toByteArray(";"),
            toByteArray("pf;"), toByteArray("cr;"), toByteArray("cy;"),
            toByteArray("cy;"), toByteArray("cy;"), toByteArray("cute"),
            toByteArray("cute;"), toByteArray("irc;"), toByteArray("y;"),
            toByteArray("r;"), toByteArray("pf;"), toByteArray("cr;"),
            toByteArray("ml;"), toByteArray("cy;"), toByteArray("cute;"),
            toByteArray("aron;"), toByteArray("y;"), toByteArray("ot;"),
            toByteArray("roWidthSpace;"), toByteArray("ta;"),
            toByteArray("r;"), toByteArray("pf;"), toByteArray("cr;"),
            toByteArray("cute"), toByteArray("cute;"), toByteArray("reve;"),
            toByteArray(";"), toByteArray("d;"), toByteArray("irc"),
            toByteArray("irc;"), toByteArray("ute"), toByteArray("ute;"),
            toByteArray("y;"), toByteArray("lig"), toByteArray("lig;"),
            toByteArray(";"), toByteArray("r;"), toByteArray("rave"),
            toByteArray("rave;"), toByteArray("efsym;"), toByteArray("eph;"),
            toByteArray("pha;"), toByteArray("acr;"), toByteArray("alg;"),
            toByteArray("p"), toByteArray("p;"), toByteArray("d;"),
            toByteArray("dand;"), toByteArray("dd;"), toByteArray("dslope;"),
            toByteArray("dv;"), toByteArray("g;"), toByteArray("ge;"),
            toByteArray("gle;"), toByteArray("gmsd;"), toByteArray("gmsdaa;"),
            toByteArray("gmsdab;"), toByteArray("gmsdac;"),
            toByteArray("gmsdad;"), toByteArray("gmsdae;"),
            toByteArray("gmsdaf;"), toByteArray("gmsdag;"),
            toByteArray("gmsdah;"), toByteArray("grt;"), toByteArray("grtvb;"),
            toByteArray("grtvbd;"), toByteArray("gsph;"), toByteArray("gst;"),
            toByteArray("gzarr;"), toByteArray("gon;"), toByteArray("pf;"),
            toByteArray(";"), toByteArray("E;"), toByteArray("acir;"),
            toByteArray("e;"), toByteArray("id;"), toByteArray("os;"),
            toByteArray("prox;"), toByteArray("proxeq;"), toByteArray("ing"),
            toByteArray("ing;"), toByteArray("cr;"), toByteArray("t;"),
            toByteArray("ymp;"), toByteArray("ympeq;"), toByteArray("ilde"),
            toByteArray("ilde;"), toByteArray("ml"), toByteArray("ml;"),
            toByteArray("conint;"), toByteArray("int;"), toByteArray("ot;"),
            toByteArray("ckcong;"), toByteArray("ckepsilon;"),
            toByteArray("ckprime;"), toByteArray("cksim;"),
            toByteArray("cksimeq;"), toByteArray("rvee;"),
            toByteArray("rwed;"), toByteArray("rwedge;"), toByteArray("rk;"),
            toByteArray("rktbrk;"), toByteArray("ong;"), toByteArray("y;"),
            toByteArray("quo;"), toByteArray("caus;"), toByteArray("cause;"),
            toByteArray("mptyv;"), toByteArray("psi;"), toByteArray("rnou;"),
            toByteArray("ta;"), toByteArray("th;"), toByteArray("tween;"),
            toByteArray("r;"), toByteArray("gcap;"), toByteArray("gcirc;"),
            toByteArray("gcup;"), toByteArray("godot;"),
            toByteArray("goplus;"), toByteArray("gotimes;"),
            toByteArray("gsqcup;"), toByteArray("gstar;"),
            toByteArray("gtriangledown;"), toByteArray("gtriangleup;"),
            toByteArray("guplus;"), toByteArray("gvee;"),
            toByteArray("gwedge;"), toByteArray("arow;"),
            toByteArray("acklozenge;"), toByteArray("acksquare;"),
            toByteArray("acktriangle;"), toByteArray("acktriangledown;"),
            toByteArray("acktriangleleft;"), toByteArray("acktriangleright;"),
            toByteArray("ank;"), toByteArray("k12;"), toByteArray("k14;"),
            toByteArray("k34;"), toByteArray("ock;"), toByteArray("ot;"),
            toByteArray("pf;"), toByteArray("t;"), toByteArray("ttom;"),
            toByteArray("wtie;"), toByteArray("xDL;"), toByteArray("xDR;"),
            toByteArray("xDl;"), toByteArray("xDr;"), toByteArray("xH;"),
            toByteArray("xHD;"), toByteArray("xHU;"), toByteArray("xHd;"),
            toByteArray("xHu;"), toByteArray("xUL;"), toByteArray("xUR;"),
            toByteArray("xUl;"), toByteArray("xUr;"), toByteArray("xV;"),
            toByteArray("xVH;"), toByteArray("xVL;"), toByteArray("xVR;"),
            toByteArray("xVh;"), toByteArray("xVl;"), toByteArray("xVr;"),
            toByteArray("xbox;"), toByteArray("xdL;"), toByteArray("xdR;"),
            toByteArray("xdl;"), toByteArray("xdr;"), toByteArray("xh;"),
            toByteArray("xhD;"), toByteArray("xhU;"), toByteArray("xhd;"),
            toByteArray("xhu;"), toByteArray("xminus;"), toByteArray("xplus;"),
            toByteArray("xtimes;"), toByteArray("xuL;"), toByteArray("xuR;"),
            toByteArray("xul;"), toByteArray("xur;"), toByteArray("xv;"),
            toByteArray("xvH;"), toByteArray("xvL;"), toByteArray("xvR;"),
            toByteArray("xvh;"), toByteArray("xvl;"), toByteArray("xvr;"),
            toByteArray("rime;"), toByteArray("eve;"), toByteArray("vbar"),
            toByteArray("vbar;"), toByteArray("cr;"), toByteArray("emi;"),
            toByteArray("im;"), toByteArray("ime;"), toByteArray("ol;"),
            toByteArray("olb;"), toByteArray("olhsub;"), toByteArray("ll;"),
            toByteArray("llet;"), toByteArray("mp;"), toByteArray("mpE;"),
            toByteArray("mpe;"), toByteArray("mpeq;"), toByteArray("cute;"),
            toByteArray("p;"), toByteArray("pand;"), toByteArray("pbrcup;"),
            toByteArray("pcap;"), toByteArray("pcup;"), toByteArray("pdot;"),
            toByteArray("ret;"), toByteArray("ron;"), toByteArray("aps;"),
            toByteArray("aron;"), toByteArray("edil"), toByteArray("edil;"),
            toByteArray("irc;"), toByteArray("ups;"), toByteArray("upssm;"),
            toByteArray("ot;"), toByteArray("dil"), toByteArray("dil;"),
            toByteArray("mptyv;"), toByteArray("nt"), toByteArray("nt;"),
            toByteArray("nterdot;"), toByteArray("r;"), toByteArray("cy;"),
            toByteArray("eck;"), toByteArray("eckmark;"), toByteArray("i;"),
            toByteArray("r;"), toByteArray("rE;"), toByteArray("rc;"),
            toByteArray("rceq;"), toByteArray("rclearrowleft;"),
            toByteArray("rclearrowright;"), toByteArray("rcledR;"),
            toByteArray("rcledS;"), toByteArray("rcledast;"),
            toByteArray("rcledcirc;"), toByteArray("rcleddash;"),
            toByteArray("re;"), toByteArray("rfnint;"), toByteArray("rmid;"),
            toByteArray("rscir;"), toByteArray("ubs;"), toByteArray("ubsuit;"),
            toByteArray("lon;"), toByteArray("lone;"), toByteArray("loneq;"),
            toByteArray("mma;"), toByteArray("mmat;"), toByteArray("mp;"),
            toByteArray("mpfn;"), toByteArray("mplement;"),
            toByteArray("mplexes;"), toByteArray("ng;"), toByteArray("ngdot;"),
            toByteArray("nint;"), toByteArray("pf;"), toByteArray("prod;"),
            toByteArray("py"), toByteArray("py;"), toByteArray("pysr;"),
            toByteArray("arr;"), toByteArray("oss;"), toByteArray("cr;"),
            toByteArray("ub;"), toByteArray("ube;"), toByteArray("up;"),
            toByteArray("upe;"), toByteArray("dot;"), toByteArray("darrl;"),
            toByteArray("darrr;"), toByteArray("epr;"), toByteArray("esc;"),
            toByteArray("larr;"), toByteArray("larrp;"), toByteArray("p;"),
            toByteArray("pbrcap;"), toByteArray("pcap;"), toByteArray("pcup;"),
            toByteArray("pdot;"), toByteArray("por;"), toByteArray("rarr;"),
            toByteArray("rarrm;"), toByteArray("rlyeqprec;"),
            toByteArray("rlyeqsucc;"), toByteArray("rlyvee;"),
            toByteArray("rlywedge;"), toByteArray("rren"),
            toByteArray("rren;"), toByteArray("rvearrowleft;"),
            toByteArray("rvearrowright;"), toByteArray("vee;"),
            toByteArray("wed;"), toByteArray("conint;"), toByteArray("int;"),
            toByteArray("lcty;"), toByteArray("rr;"), toByteArray("ar;"),
            toByteArray("gger;"), toByteArray("leth;"), toByteArray("rr;"),
            toByteArray("sh;"), toByteArray("shv;"), toByteArray("karow;"),
            toByteArray("lac;"), toByteArray("aron;"), toByteArray("y;"),
            toByteArray(";"), toByteArray("agger;"), toByteArray("arr;"),
            toByteArray("otseq;"), toByteArray("g"), toByteArray("g;"),
            toByteArray("lta;"), toByteArray("mptyv;"), toByteArray("isht;"),
            toByteArray("r;"), toByteArray("arl;"), toByteArray("arr;"),
            toByteArray("am;"), toByteArray("amond;"),
            toByteArray("amondsuit;"), toByteArray("ams;"), toByteArray("e;"),
            toByteArray("gamma;"), toByteArray("sin;"), toByteArray("v;"),
            toByteArray("vide"), toByteArray("vide;"),
            toByteArray("videontimes;"), toByteArray("vonx;"),
            toByteArray("cy;"), toByteArray("corn;"), toByteArray("crop;"),
            toByteArray("llar;"), toByteArray("pf;"), toByteArray("t;"),
            toByteArray("teq;"), toByteArray("teqdot;"),
            toByteArray("tminus;"), toByteArray("tplus;"),
            toByteArray("tsquare;"), toByteArray("ublebarwedge;"),
            toByteArray("wnarrow;"), toByteArray("wndownarrows;"),
            toByteArray("wnharpoonleft;"), toByteArray("wnharpoonright;"),
            toByteArray("bkarow;"), toByteArray("corn;"), toByteArray("crop;"),
            toByteArray("cr;"), toByteArray("cy;"), toByteArray("ol;"),
            toByteArray("trok;"), toByteArray("dot;"), toByteArray("ri;"),
            toByteArray("rif;"), toByteArray("arr;"), toByteArray("har;"),
            toByteArray("angle;"), toByteArray("cy;"), toByteArray("igrarr;"),
            toByteArray("Dot;"), toByteArray("ot;"), toByteArray("cute"),
            toByteArray("cute;"), toByteArray("ster;"), toByteArray("aron;"),
            toByteArray("ir;"), toByteArray("irc"), toByteArray("irc;"),
            toByteArray("olon;"), toByteArray("y;"), toByteArray("ot;"),
            toByteArray(";"), toByteArray("Dot;"), toByteArray("r;"),
            toByteArray(";"), toByteArray("rave"), toByteArray("rave;"),
            toByteArray("s;"), toByteArray("sdot;"), toByteArray(";"),
            toByteArray("inters;"), toByteArray("l;"), toByteArray("s;"),
            toByteArray("sdot;"), toByteArray("acr;"), toByteArray("pty;"),
            toByteArray("ptyset;"), toByteArray("ptyv;"), toByteArray("sp13;"),
            toByteArray("sp14;"), toByteArray("sp;"), toByteArray("g;"),
            toByteArray("sp;"), toByteArray("gon;"), toByteArray("pf;"),
            toByteArray("ar;"), toByteArray("arsl;"), toByteArray("lus;"),
            toByteArray("si;"), toByteArray("silon;"), toByteArray("siv;"),
            toByteArray("circ;"), toByteArray("colon;"), toByteArray("sim;"),
            toByteArray("slantgtr;"), toByteArray("slantless;"),
            toByteArray("uals;"), toByteArray("uest;"), toByteArray("uiv;"),
            toByteArray("uivDD;"), toByteArray("vparsl;"), toByteArray("Dot;"),
            toByteArray("arr;"), toByteArray("cr;"), toByteArray("dot;"),
            toByteArray("im;"), toByteArray("a;"), toByteArray("h"),
            toByteArray("h;"), toByteArray("ml"), toByteArray("ml;"),
            toByteArray("ro;"), toByteArray("cl;"), toByteArray("ist;"),
            toByteArray("pectation;"), toByteArray("ponentiale;"),
            toByteArray("llingdotseq;"), toByteArray("y;"),
            toByteArray("male;"), toByteArray("ilig;"), toByteArray("lig;"),
            toByteArray("llig;"), toByteArray("r;"), toByteArray("lig;"),
            toByteArray("at;"), toByteArray("lig;"), toByteArray("tns;"),
            toByteArray("of;"), toByteArray("pf;"), toByteArray("rall;"),
            toByteArray("rk;"), toByteArray("rkv;"), toByteArray("artint;"),
            toByteArray("ac12"), toByteArray("ac12;"), toByteArray("ac13;"),
            toByteArray("ac14"), toByteArray("ac14;"), toByteArray("ac15;"),
            toByteArray("ac16;"), toByteArray("ac18;"), toByteArray("ac23;"),
            toByteArray("ac25;"), toByteArray("ac34"), toByteArray("ac34;"),
            toByteArray("ac35;"), toByteArray("ac38;"), toByteArray("ac45;"),
            toByteArray("ac56;"), toByteArray("ac58;"), toByteArray("ac78;"),
            toByteArray("asl;"), toByteArray("own;"), toByteArray("cr;"),
            toByteArray(";"), toByteArray("l;"), toByteArray("cute;"),
            toByteArray("mma;"), toByteArray("mmad;"), toByteArray("p;"),
            toByteArray("reve;"), toByteArray("irc;"), toByteArray("y;"),
            toByteArray("ot;"), toByteArray(";"), toByteArray("l;"),
            toByteArray("q;"), toByteArray("qq;"), toByteArray("qslant;"),
            toByteArray("s;"), toByteArray("scc;"), toByteArray("sdot;"),
            toByteArray("sdoto;"), toByteArray("sdotol;"),
            toByteArray("sles;"), toByteArray("r;"), toByteArray(";"),
            toByteArray("g;"), toByteArray("mel;"), toByteArray("cy;"),
            toByteArray(";"), toByteArray("E;"), toByteArray("a;"),
            toByteArray("j;"), toByteArray("E;"), toByteArray("ap;"),
            toByteArray("approx;"), toByteArray("e;"), toByteArray("eq;"),
            toByteArray("eqq;"), toByteArray("sim;"), toByteArray("pf;"),
            toByteArray("ave;"), toByteArray("cr;"), toByteArray("im;"),
            toByteArray("ime;"), toByteArray("iml;"), toByteArray(""),
            toByteArray(";"), toByteArray("cc;"), toByteArray("cir;"),
            toByteArray("dot;"), toByteArray("lPar;"), toByteArray("quest;"),
            toByteArray("rapprox;"), toByteArray("rarr;"),
            toByteArray("rdot;"), toByteArray("reqless;"),
            toByteArray("reqqless;"), toByteArray("rless;"),
            toByteArray("rsim;"), toByteArray("rr;"), toByteArray("irsp;"),
            toByteArray("lf;"), toByteArray("milt;"), toByteArray("rdcy;"),
            toByteArray("rr;"), toByteArray("rrcir;"), toByteArray("rrw;"),
            toByteArray("ar;"), toByteArray("irc;"), toByteArray("arts;"),
            toByteArray("artsuit;"), toByteArray("llip;"),
            toByteArray("rcon;"), toByteArray("r;"), toByteArray("searow;"),
            toByteArray("swarow;"), toByteArray("arr;"), toByteArray("mtht;"),
            toByteArray("okleftarrow;"), toByteArray("okrightarrow;"),
            toByteArray("pf;"), toByteArray("rbar;"), toByteArray("cr;"),
            toByteArray("lash;"), toByteArray("trok;"), toByteArray("bull;"),
            toByteArray("phen;"), toByteArray("cute"), toByteArray("cute;"),
            toByteArray(";"), toByteArray("irc"), toByteArray("irc;"),
            toByteArray("y;"), toByteArray("cy;"), toByteArray("xcl"),
            toByteArray("xcl;"), toByteArray("f;"), toByteArray("r;"),
            toByteArray("rave"), toByteArray("rave;"), toByteArray(";"),
            toByteArray("iint;"), toByteArray("int;"), toByteArray("nfin;"),
            toByteArray("ota;"), toByteArray("lig;"), toByteArray("acr;"),
            toByteArray("age;"), toByteArray("agline;"),
            toByteArray("agpart;"), toByteArray("ath;"), toByteArray("of;"),
            toByteArray("ped;"), toByteArray(";"), toByteArray("care;"),
            toByteArray("fin;"), toByteArray("fintie;"), toByteArray("odot;"),
            toByteArray("t;"), toByteArray("tcal;"), toByteArray("tegers;"),
            toByteArray("tercal;"), toByteArray("tlarhk;"),
            toByteArray("tprod;"), toByteArray("cy;"), toByteArray("gon;"),
            toByteArray("pf;"), toByteArray("ta;"), toByteArray("rod;"),
            toByteArray("uest"), toByteArray("uest;"), toByteArray("cr;"),
            toByteArray("in;"), toByteArray("inE;"), toByteArray("indot;"),
            toByteArray("ins;"), toByteArray("insv;"), toByteArray("inv;"),
            toByteArray(";"), toByteArray("ilde;"), toByteArray("kcy;"),
            toByteArray("ml"), toByteArray("ml;"), toByteArray("irc;"),
            toByteArray("y;"), toByteArray("r;"), toByteArray("ath;"),
            toByteArray("pf;"), toByteArray("cr;"), toByteArray("ercy;"),
            toByteArray("kcy;"), toByteArray("ppa;"), toByteArray("ppav;"),
            toByteArray("edil;"), toByteArray("y;"), toByteArray("r;"),
            toByteArray("reen;"), toByteArray("cy;"), toByteArray("cy;"),
            toByteArray("pf;"), toByteArray("cr;"), toByteArray("arr;"),
            toByteArray("rr;"), toByteArray("tail;"), toByteArray("arr;"),
            toByteArray(";"), toByteArray("g;"), toByteArray("ar;"),
            toByteArray("cute;"), toByteArray("emptyv;"), toByteArray("gran;"),
            toByteArray("mbda;"), toByteArray("ng;"), toByteArray("ngd;"),
            toByteArray("ngle;"), toByteArray("p;"), toByteArray("quo"),
            toByteArray("quo;"), toByteArray("rr;"), toByteArray("rrb;"),
            toByteArray("rrbfs;"), toByteArray("rrfs;"), toByteArray("rrhk;"),
            toByteArray("rrlp;"), toByteArray("rrpl;"), toByteArray("rrsim;"),
            toByteArray("rrtl;"), toByteArray("t;"), toByteArray("tail;"),
            toByteArray("te;"), toByteArray("arr;"), toByteArray("brk;"),
            toByteArray("race;"), toByteArray("rack;"), toByteArray("rke;"),
            toByteArray("rksld;"), toByteArray("rkslu;"), toByteArray("aron;"),
            toByteArray("edil;"), toByteArray("eil;"), toByteArray("ub;"),
            toByteArray("y;"), toByteArray("ca;"), toByteArray("quo;"),
            toByteArray("quor;"), toByteArray("rdhar;"),
            toByteArray("rushar;"), toByteArray("sh;"), toByteArray(";"),
            toByteArray("ftarrow;"), toByteArray("ftarrowtail;"),
            toByteArray("ftharpoondown;"), toByteArray("ftharpoonup;"),
            toByteArray("ftleftarrows;"), toByteArray("ftrightarrow;"),
            toByteArray("ftrightarrows;"), toByteArray("ftrightharpoons;"),
            toByteArray("ftrightsquigarrow;"), toByteArray("ftthreetimes;"),
            toByteArray("g;"), toByteArray("q;"), toByteArray("qq;"),
            toByteArray("qslant;"), toByteArray("s;"), toByteArray("scc;"),
            toByteArray("sdot;"), toByteArray("sdoto;"),
            toByteArray("sdotor;"), toByteArray("sges;"),
            toByteArray("ssapprox;"), toByteArray("ssdot;"),
            toByteArray("sseqgtr;"), toByteArray("sseqqgtr;"),
            toByteArray("ssgtr;"), toByteArray("sssim;"), toByteArray("isht;"),
            toByteArray("loor;"), toByteArray("r;"), toByteArray(";"),
            toByteArray("E;"), toByteArray("ard;"), toByteArray("aru;"),
            toByteArray("arul;"), toByteArray("blk;"), toByteArray("cy;"),
            toByteArray(";"), toByteArray("arr;"), toByteArray("corner;"),
            toByteArray("hard;"), toByteArray("tri;"), toByteArray("idot;"),
            toByteArray("oust;"), toByteArray("oustache;"), toByteArray("E;"),
            toByteArray("ap;"), toByteArray("approx;"), toByteArray("e;"),
            toByteArray("eq;"), toByteArray("eqq;"), toByteArray("sim;"),
            toByteArray("ang;"), toByteArray("arr;"), toByteArray("brk;"),
            toByteArray("ngleftarrow;"), toByteArray("ngleftrightarrow;"),
            toByteArray("ngmapsto;"), toByteArray("ngrightarrow;"),
            toByteArray("oparrowleft;"), toByteArray("oparrowright;"),
            toByteArray("par;"), toByteArray("pf;"), toByteArray("plus;"),
            toByteArray("times;"), toByteArray("wast;"), toByteArray("wbar;"),
            toByteArray("z;"), toByteArray("zenge;"), toByteArray("zf;"),
            toByteArray("ar;"), toByteArray("arlt;"), toByteArray("arr;"),
            toByteArray("corner;"), toByteArray("har;"), toByteArray("hard;"),
            toByteArray("m;"), toByteArray("tri;"), toByteArray("aquo;"),
            toByteArray("cr;"), toByteArray("h;"), toByteArray("im;"),
            toByteArray("ime;"), toByteArray("img;"), toByteArray("qb;"),
            toByteArray("quo;"), toByteArray("quor;"), toByteArray("trok;"),
            toByteArray(""), toByteArray(";"), toByteArray("cc;"),
            toByteArray("cir;"), toByteArray("dot;"), toByteArray("hree;"),
            toByteArray("imes;"), toByteArray("larr;"), toByteArray("quest;"),
            toByteArray("rPar;"), toByteArray("ri;"), toByteArray("rie;"),
            toByteArray("rif;"), toByteArray("rdshar;"), toByteArray("ruhar;"),
            toByteArray("Dot;"), toByteArray("cr"), toByteArray("cr;"),
            toByteArray("le;"), toByteArray("lt;"), toByteArray("ltese;"),
            toByteArray("p;"), toByteArray("psto;"), toByteArray("pstodown;"),
            toByteArray("pstoleft;"), toByteArray("pstoup;"),
            toByteArray("rker;"), toByteArray("omma;"), toByteArray("y;"),
            toByteArray("ash;"), toByteArray("asuredangle;"),
            toByteArray("r;"), toByteArray("o;"), toByteArray("cro"),
            toByteArray("cro;"), toByteArray("d;"), toByteArray("dast;"),
            toByteArray("dcir;"), toByteArray("ddot"), toByteArray("ddot;"),
            toByteArray("nus;"), toByteArray("nusb;"), toByteArray("nusd;"),
            toByteArray("nusdu;"), toByteArray("cp;"), toByteArray("dr;"),
            toByteArray("plus;"), toByteArray("dels;"), toByteArray("pf;"),
            toByteArray(";"), toByteArray("cr;"), toByteArray("tpos;"),
            toByteArray(";"), toByteArray("ltimap;"), toByteArray("map;"),
            toByteArray("eftarrow;"), toByteArray("eftrightarrow;"),
            toByteArray("ightarrow;"), toByteArray("Dash;"),
            toByteArray("dash;"), toByteArray("bla;"), toByteArray("cute;"),
            toByteArray("p;"), toByteArray("pos;"), toByteArray("pprox;"),
            toByteArray("tur;"), toByteArray("tural;"), toByteArray("turals;"),
            toByteArray("sp"), toByteArray("sp;"), toByteArray("ap;"),
            toByteArray("aron;"), toByteArray("edil;"), toByteArray("ong;"),
            toByteArray("up;"), toByteArray("y;"), toByteArray("ash;"),
            toByteArray(";"), toByteArray("Arr;"), toByteArray("arhk;"),
            toByteArray("arr;"), toByteArray("arrow;"), toByteArray("quiv;"),
            toByteArray("sear;"), toByteArray("xist;"), toByteArray("xists;"),
            toByteArray("r;"), toByteArray("e;"), toByteArray("eq;"),
            toByteArray("sim;"), toByteArray("t;"), toByteArray("tr;"),
            toByteArray("Arr;"), toByteArray("arr;"), toByteArray("par;"),
            toByteArray(";"), toByteArray("s;"), toByteArray("sd;"),
            toByteArray("v;"), toByteArray("cy;"), toByteArray("Arr;"),
            toByteArray("arr;"), toByteArray("dr;"), toByteArray("e;"),
            toByteArray("eftarrow;"), toByteArray("eftrightarrow;"),
            toByteArray("eq;"), toByteArray("ess;"), toByteArray("sim;"),
            toByteArray("t;"), toByteArray("tri;"), toByteArray("trie;"),
            toByteArray("id;"), toByteArray("pf;"), toByteArray("t"),
            toByteArray("t;"), toByteArray("tin;"), toByteArray("tinva;"),
            toByteArray("tinvb;"), toByteArray("tinvc;"), toByteArray("tni;"),
            toByteArray("tniva;"), toByteArray("tnivb;"),
            toByteArray("tnivc;"), toByteArray("ar;"), toByteArray("arallel;"),
            toByteArray("olint;"), toByteArray("r;"), toByteArray("rcue;"),
            toByteArray("rec;"), toByteArray("Arr;"), toByteArray("arr;"),
            toByteArray("ightarrow;"), toByteArray("tri;"),
            toByteArray("trie;"), toByteArray("c;"), toByteArray("ccue;"),
            toByteArray("cr;"), toByteArray("hortmid;"),
            toByteArray("hortparallel;"), toByteArray("im;"),
            toByteArray("ime;"), toByteArray("imeq;"), toByteArray("mid;"),
            toByteArray("par;"), toByteArray("qsube;"), toByteArray("qsupe;"),
            toByteArray("ub;"), toByteArray("ube;"), toByteArray("ubseteq;"),
            toByteArray("ucc;"), toByteArray("up;"), toByteArray("upe;"),
            toByteArray("upseteq;"), toByteArray("gl;"), toByteArray("ilde"),
            toByteArray("ilde;"), toByteArray("lg;"),
            toByteArray("riangleleft;"), toByteArray("rianglelefteq;"),
            toByteArray("riangleright;"), toByteArray("rianglerighteq;"),
            toByteArray(";"), toByteArray("m;"), toByteArray("mero;"),
            toByteArray("msp;"), toByteArray("Dash;"), toByteArray("Harr;"),
            toByteArray("dash;"), toByteArray("infin;"), toByteArray("lArr;"),
            toByteArray("rArr;"), toByteArray("Arr;"), toByteArray("arhk;"),
            toByteArray("arr;"), toByteArray("arrow;"), toByteArray("near;"),
            toByteArray(";"), toByteArray("cute"), toByteArray("cute;"),
            toByteArray("st;"), toByteArray("ir;"), toByteArray("irc"),
            toByteArray("irc;"), toByteArray("y;"), toByteArray("ash;"),
            toByteArray("blac;"), toByteArray("iv;"), toByteArray("ot;"),
            toByteArray("sold;"), toByteArray("lig;"), toByteArray("cir;"),
            toByteArray("r;"), toByteArray("on;"), toByteArray("rave"),
            toByteArray("rave;"), toByteArray("t;"), toByteArray("bar;"),
            toByteArray("m;"), toByteArray("nt;"), toByteArray("arr;"),
            toByteArray("cir;"), toByteArray("cross;"), toByteArray("ine;"),
            toByteArray("t;"), toByteArray("acr;"), toByteArray("ega;"),
            toByteArray("icron;"), toByteArray("id;"), toByteArray("inus;"),
            toByteArray("pf;"), toByteArray("ar;"), toByteArray("erp;"),
            toByteArray("lus;"), toByteArray(";"), toByteArray("arr;"),
            toByteArray("d;"), toByteArray("der;"), toByteArray("derof;"),
            toByteArray("df"), toByteArray("df;"), toByteArray("dm"),
            toByteArray("dm;"), toByteArray("igof;"), toByteArray("or;"),
            toByteArray("slope;"), toByteArray("v;"), toByteArray("cr;"),
            toByteArray("lash"), toByteArray("lash;"), toByteArray("ol;"),
            toByteArray("ilde"), toByteArray("ilde;"), toByteArray("imes;"),
            toByteArray("imesas;"), toByteArray("ml"), toByteArray("ml;"),
            toByteArray("bar;"), toByteArray("r;"), toByteArray("ra"),
            toByteArray("ra;"), toByteArray("rallel;"), toByteArray("rsim;"),
            toByteArray("rsl;"), toByteArray("rt;"), toByteArray("y;"),
            toByteArray("rcnt;"), toByteArray("riod;"), toByteArray("rmil;"),
            toByteArray("rp;"), toByteArray("rtenk;"), toByteArray("r;"),
            toByteArray("i;"), toByteArray("iv;"), toByteArray("mmat;"),
            toByteArray("one;"), toByteArray(";"), toByteArray("tchfork;"),
            toByteArray("v;"), toByteArray("anck;"), toByteArray("anckh;"),
            toByteArray("ankv;"), toByteArray("us;"), toByteArray("usacir;"),
            toByteArray("usb;"), toByteArray("uscir;"), toByteArray("usdo;"),
            toByteArray("usdu;"), toByteArray("use;"), toByteArray("usmn"),
            toByteArray("usmn;"), toByteArray("ussim;"), toByteArray("ustwo;"),
            toByteArray(";"), toByteArray("intint;"), toByteArray("pf;"),
            toByteArray("und"), toByteArray("und;"), toByteArray(";"),
            toByteArray("E;"), toByteArray("ap;"), toByteArray("cue;"),
            toByteArray("e;"), toByteArray("ec;"), toByteArray("ecapprox;"),
            toByteArray("eccurlyeq;"), toByteArray("eceq;"),
            toByteArray("ecnapprox;"), toByteArray("ecneqq;"),
            toByteArray("ecnsim;"), toByteArray("ecsim;"), toByteArray("ime;"),
            toByteArray("imes;"), toByteArray("nE;"), toByteArray("nap;"),
            toByteArray("nsim;"), toByteArray("od;"), toByteArray("ofalar;"),
            toByteArray("ofline;"), toByteArray("ofsurf;"), toByteArray("op;"),
            toByteArray("opto;"), toByteArray("sim;"), toByteArray("urel;"),
            toByteArray("cr;"), toByteArray("i;"), toByteArray("ncsp;"),
            toByteArray("r;"), toByteArray("nt;"), toByteArray("pf;"),
            toByteArray("rime;"), toByteArray("cr;"),
            toByteArray("aternions;"), toByteArray("atint;"),
            toByteArray("est;"), toByteArray("esteq;"), toByteArray("ot"),
            toByteArray("ot;"), toByteArray("arr;"), toByteArray("rr;"),
            toByteArray("tail;"), toByteArray("arr;"), toByteArray("ar;"),
            toByteArray("cute;"), toByteArray("dic;"), toByteArray("emptyv;"),
            toByteArray("ng;"), toByteArray("ngd;"), toByteArray("nge;"),
            toByteArray("ngle;"), toByteArray("quo"), toByteArray("quo;"),
            toByteArray("rr;"), toByteArray("rrap;"), toByteArray("rrb;"),
            toByteArray("rrbfs;"), toByteArray("rrc;"), toByteArray("rrfs;"),
            toByteArray("rrhk;"), toByteArray("rrlp;"), toByteArray("rrpl;"),
            toByteArray("rrsim;"), toByteArray("rrtl;"), toByteArray("rrw;"),
            toByteArray("tail;"), toByteArray("tio;"), toByteArray("tionals;"),
            toByteArray("arr;"), toByteArray("brk;"), toByteArray("race;"),
            toByteArray("rack;"), toByteArray("rke;"), toByteArray("rksld;"),
            toByteArray("rkslu;"), toByteArray("aron;"), toByteArray("edil;"),
            toByteArray("eil;"), toByteArray("ub;"), toByteArray("y;"),
            toByteArray("ca;"), toByteArray("ldhar;"), toByteArray("quo;"),
            toByteArray("quor;"), toByteArray("sh;"), toByteArray("al;"),
            toByteArray("aline;"), toByteArray("alpart;"), toByteArray("als;"),
            toByteArray("ct;"), toByteArray("g"), toByteArray("g;"),
            toByteArray("isht;"), toByteArray("loor;"), toByteArray("r;"),
            toByteArray("ard;"), toByteArray("aru;"), toByteArray("arul;"),
            toByteArray("o;"), toByteArray("ov;"), toByteArray("ghtarrow;"),
            toByteArray("ghtarrowtail;"), toByteArray("ghtharpoondown;"),
            toByteArray("ghtharpoonup;"), toByteArray("ghtleftarrows;"),
            toByteArray("ghtleftharpoons;"), toByteArray("ghtrightarrows;"),
            toByteArray("ghtsquigarrow;"), toByteArray("ghtthreetimes;"),
            toByteArray("ng;"), toByteArray("singdotseq;"),
            toByteArray("arr;"), toByteArray("har;"), toByteArray("m;"),
            toByteArray("oust;"), toByteArray("oustache;"),
            toByteArray("mid;"), toByteArray("ang;"), toByteArray("arr;"),
            toByteArray("brk;"), toByteArray("par;"), toByteArray("pf;"),
            toByteArray("plus;"), toByteArray("times;"), toByteArray("ar;"),
            toByteArray("argt;"), toByteArray("polint;"), toByteArray("arr;"),
            toByteArray("aquo;"), toByteArray("cr;"), toByteArray("h;"),
            toByteArray("qb;"), toByteArray("quo;"), toByteArray("quor;"),
            toByteArray("hree;"), toByteArray("imes;"), toByteArray("ri;"),
            toByteArray("rie;"), toByteArray("rif;"), toByteArray("riltri;"),
            toByteArray("luhar;"), toByteArray(";"), toByteArray("cute;"),
            toByteArray("quo;"), toByteArray(";"), toByteArray("E;"),
            toByteArray("ap;"), toByteArray("aron;"), toByteArray("cue;"),
            toByteArray("e;"), toByteArray("edil;"), toByteArray("irc;"),
            toByteArray("nE;"), toByteArray("nap;"), toByteArray("nsim;"),
            toByteArray("polint;"), toByteArray("sim;"), toByteArray("y;"),
            toByteArray("ot;"), toByteArray("otb;"), toByteArray("ote;"),
            toByteArray("Arr;"), toByteArray("arhk;"), toByteArray("arr;"),
            toByteArray("arrow;"), toByteArray("ct"), toByteArray("ct;"),
            toByteArray("mi;"), toByteArray("swar;"), toByteArray("tminus;"),
            toByteArray("tmn;"), toByteArray("xt;"), toByteArray("r;"),
            toByteArray("rown;"), toByteArray("arp;"), toByteArray("chcy;"),
            toByteArray("cy;"), toByteArray("ortmid;"),
            toByteArray("ortparallel;"), toByteArray("y"), toByteArray("y;"),
            toByteArray("gma;"), toByteArray("gmaf;"), toByteArray("gmav;"),
            toByteArray("m;"), toByteArray("mdot;"), toByteArray("me;"),
            toByteArray("meq;"), toByteArray("mg;"), toByteArray("mgE;"),
            toByteArray("ml;"), toByteArray("mlE;"), toByteArray("mne;"),
            toByteArray("mplus;"), toByteArray("mrarr;"), toByteArray("arr;"),
            toByteArray("allsetminus;"), toByteArray("ashp;"),
            toByteArray("eparsl;"), toByteArray("id;"), toByteArray("ile;"),
            toByteArray("t;"), toByteArray("te;"), toByteArray("ftcy;"),
            toByteArray("l;"), toByteArray("lb;"), toByteArray("lbar;"),
            toByteArray("pf;"), toByteArray("ades;"), toByteArray("adesuit;"),
            toByteArray("ar;"), toByteArray("cap;"), toByteArray("cup;"),
            toByteArray("sub;"), toByteArray("sube;"), toByteArray("subset;"),
            toByteArray("subseteq;"), toByteArray("sup;"),
            toByteArray("supe;"), toByteArray("supset;"),
            toByteArray("supseteq;"), toByteArray("u;"), toByteArray("uare;"),
            toByteArray("uarf;"), toByteArray("uf;"), toByteArray("arr;"),
            toByteArray("cr;"), toByteArray("etmn;"), toByteArray("mile;"),
            toByteArray("tarf;"), toByteArray("ar;"), toByteArray("arf;"),
            toByteArray("raightepsilon;"), toByteArray("raightphi;"),
            toByteArray("rns;"), toByteArray("b;"), toByteArray("bE;"),
            toByteArray("bdot;"), toByteArray("be;"), toByteArray("bedot;"),
            toByteArray("bmult;"), toByteArray("bnE;"), toByteArray("bne;"),
            toByteArray("bplus;"), toByteArray("brarr;"), toByteArray("bset;"),
            toByteArray("bseteq;"), toByteArray("bseteqq;"),
            toByteArray("bsetneq;"), toByteArray("bsetneqq;"),
            toByteArray("bsim;"), toByteArray("bsub;"), toByteArray("bsup;"),
            toByteArray("cc;"), toByteArray("ccapprox;"),
            toByteArray("cccurlyeq;"), toByteArray("cceq;"),
            toByteArray("ccnapprox;"), toByteArray("ccneqq;"),
            toByteArray("ccnsim;"), toByteArray("ccsim;"), toByteArray("m;"),
            toByteArray("ng;"), toByteArray("p1"), toByteArray("p1;"),
            toByteArray("p2"), toByteArray("p2;"), toByteArray("p3"),
            toByteArray("p3;"), toByteArray("p;"), toByteArray("pE;"),
            toByteArray("pdot;"), toByteArray("pdsub;"), toByteArray("pe;"),
            toByteArray("pedot;"), toByteArray("phsol;"),
            toByteArray("phsub;"), toByteArray("plarr;"),
            toByteArray("pmult;"), toByteArray("pnE;"), toByteArray("pne;"),
            toByteArray("pplus;"), toByteArray("pset;"),
            toByteArray("pseteq;"), toByteArray("pseteqq;"),
            toByteArray("psetneq;"), toByteArray("psetneqq;"),
            toByteArray("psim;"), toByteArray("psub;"), toByteArray("psup;"),
            toByteArray("Arr;"), toByteArray("arhk;"), toByteArray("arr;"),
            toByteArray("arrow;"), toByteArray("nwar;"), toByteArray("lig"),
            toByteArray("lig;"), toByteArray("rget;"), toByteArray("u;"),
            toByteArray("rk;"), toByteArray("aron;"), toByteArray("edil;"),
            toByteArray("y;"), toByteArray("ot;"), toByteArray("lrec;"),
            toByteArray("r;"), toByteArray("ere4;"), toByteArray("erefore;"),
            toByteArray("eta;"), toByteArray("etasym;"), toByteArray("etav;"),
            toByteArray("ickapprox;"), toByteArray("icksim;"),
            toByteArray("insp;"), toByteArray("kap;"), toByteArray("ksim;"),
            toByteArray("orn"), toByteArray("orn;"), toByteArray("lde;"),
            toByteArray("mes"), toByteArray("mes;"), toByteArray("mesb;"),
            toByteArray("mesbar;"), toByteArray("mesd;"), toByteArray("nt;"),
            toByteArray("ea;"), toByteArray("p;"), toByteArray("pbot;"),
            toByteArray("pcir;"), toByteArray("pf;"), toByteArray("pfork;"),
            toByteArray("sa;"), toByteArray("rime;"), toByteArray("ade;"),
            toByteArray("iangle;"), toByteArray("iangledown;"),
            toByteArray("iangleleft;"), toByteArray("ianglelefteq;"),
            toByteArray("iangleq;"), toByteArray("iangleright;"),
            toByteArray("ianglerighteq;"), toByteArray("idot;"),
            toByteArray("ie;"), toByteArray("iminus;"), toByteArray("iplus;"),
            toByteArray("isb;"), toByteArray("itime;"), toByteArray("pezium;"),
            toByteArray("cr;"), toByteArray("cy;"), toByteArray("hcy;"),
            toByteArray("trok;"), toByteArray("ixt;"),
            toByteArray("oheadleftarrow;"), toByteArray("oheadrightarrow;"),
            toByteArray("rr;"), toByteArray("ar;"), toByteArray("cute"),
            toByteArray("cute;"), toByteArray("rr;"), toByteArray("rcy;"),
            toByteArray("reve;"), toByteArray("irc"), toByteArray("irc;"),
            toByteArray("y;"), toByteArray("arr;"), toByteArray("blac;"),
            toByteArray("har;"), toByteArray("isht;"), toByteArray("r;"),
            toByteArray("rave"), toByteArray("rave;"), toByteArray("arl;"),
            toByteArray("arr;"), toByteArray("blk;"), toByteArray("corn;"),
            toByteArray("corner;"), toByteArray("crop;"), toByteArray("tri;"),
            toByteArray("acr;"), toByteArray("l"), toByteArray("l;"),
            toByteArray("gon;"), toByteArray("pf;"), toByteArray("arrow;"),
            toByteArray("downarrow;"), toByteArray("harpoonleft;"),
            toByteArray("harpoonright;"), toByteArray("lus;"),
            toByteArray("si;"), toByteArray("sih;"), toByteArray("silon;"),
            toByteArray("uparrows;"), toByteArray("corn;"),
            toByteArray("corner;"), toByteArray("crop;"), toByteArray("ing;"),
            toByteArray("tri;"), toByteArray("cr;"), toByteArray("dot;"),
            toByteArray("ilde;"), toByteArray("ri;"), toByteArray("rif;"),
            toByteArray("arr;"), toByteArray("ml"), toByteArray("ml;"),
            toByteArray("angle;"), toByteArray("rr;"), toByteArray("ar;"),
            toByteArray("arv;"), toByteArray("ash;"), toByteArray("ngrt;"),
            toByteArray("repsilon;"), toByteArray("rkappa;"),
            toByteArray("rnothing;"), toByteArray("rphi;"),
            toByteArray("rpi;"), toByteArray("rpropto;"), toByteArray("rr;"),
            toByteArray("rrho;"), toByteArray("rsigma;"),
            toByteArray("rtheta;"), toByteArray("rtriangleleft;"),
            toByteArray("rtriangleright;"), toByteArray("y;"),
            toByteArray("ash;"), toByteArray("e;"), toByteArray("ebar;"),
            toByteArray("eeq;"), toByteArray("llip;"), toByteArray("rbar;"),
            toByteArray("rt;"), toByteArray("r;"), toByteArray("tri;"),
            toByteArray("pf;"), toByteArray("rop;"), toByteArray("tri;"),
            toByteArray("cr;"), toByteArray("igzag;"), toByteArray("irc;"),
            toByteArray("dbar;"), toByteArray("dge;"), toByteArray("dgeq;"),
            toByteArray("ierp;"), toByteArray("r;"), toByteArray("pf;"),
            toByteArray(";"), toByteArray(";"), toByteArray("eath;"),
            toByteArray("cr;"), toByteArray("ap;"), toByteArray("irc;"),
            toByteArray("up;"), toByteArray("tri;"), toByteArray("r;"),
            toByteArray("Arr;"), toByteArray("arr;"), toByteArray(";"),
            toByteArray("Arr;"), toByteArray("arr;"), toByteArray("ap;"),
            toByteArray("is;"), toByteArray("dot;"), toByteArray("pf;"),
            toByteArray("plus;"), toByteArray("time;"), toByteArray("Arr;"),
            toByteArray("arr;"), toByteArray("cr;"), toByteArray("qcup;"),
            toByteArray("plus;"), toByteArray("tri;"), toByteArray("ee;"),
            toByteArray("edge;"), toByteArray("cute"), toByteArray("cute;"),
            toByteArray("cy;"), toByteArray("irc;"), toByteArray("y;"),
            toByteArray("n"), toByteArray("n;"), toByteArray("r;"),
            toByteArray("cy;"), toByteArray("pf;"), toByteArray("cr;"),
            toByteArray("cy;"), toByteArray("ml"), toByteArray("ml;"),
            toByteArray("cute;"), toByteArray("aron;"), toByteArray("y;"),
            toByteArray("ot;"), toByteArray("etrf;"), toByteArray("ta;"),
            toByteArray("r;"), toByteArray("cy;"), toByteArray("grarr;"),
            toByteArray("pf;"), toByteArray("cr;"), toByteArray("j;"),
            toByteArray("nj;"), };

    static final @NoLength char[][] VALUES = { { '\u00c6' }, { '\u00c6' },
            { '\u0026' }, { '\u0026' }, { '\u00c1' }, { '\u00c1' },
            { '\u0102' }, { '\u00c2' }, { '\u00c2' }, { '\u0410' },
            { '\ud835', '\udd04' }, { '\u00c0' }, { '\u00c0' }, { '\u0391' },
            { '\u0100' }, { '\u2a53' }, { '\u0104' }, { '\ud835', '\udd38' },
            { '\u2061' }, { '\u00c5' }, { '\u00c5' }, { '\ud835', '\udc9c' },
            { '\u2254' }, { '\u00c3' }, { '\u00c3' }, { '\u00c4' },
            { '\u00c4' }, { '\u2216' }, { '\u2ae7' }, { '\u2306' },
            { '\u0411' }, { '\u2235' }, { '\u212c' }, { '\u0392' },
            { '\ud835', '\udd05' }, { '\ud835', '\udd39' }, { '\u02d8' },
            { '\u212c' }, { '\u224e' }, { '\u0427' }, { '\u00a9' },
            { '\u00a9' }, { '\u0106' }, { '\u22d2' }, { '\u2145' },
            { '\u212d' }, { '\u010c' }, { '\u00c7' }, { '\u00c7' },
            { '\u0108' }, { '\u2230' }, { '\u010a' }, { '\u00b8' },
            { '\u00b7' }, { '\u212d' }, { '\u03a7' }, { '\u2299' },
            { '\u2296' }, { '\u2295' }, { '\u2297' }, { '\u2232' },
            { '\u201d' }, { '\u2019' }, { '\u2237' }, { '\u2a74' },
            { '\u2261' }, { '\u222f' }, { '\u222e' }, { '\u2102' },
            { '\u2210' }, { '\u2233' }, { '\u2a2f' }, { '\ud835', '\udc9e' },
            { '\u22d3' }, { '\u224d' }, { '\u2145' }, { '\u2911' },
            { '\u0402' }, { '\u0405' }, { '\u040f' }, { '\u2021' },
            { '\u21a1' }, { '\u2ae4' }, { '\u010e' }, { '\u0414' },
            { '\u2207' }, { '\u0394' }, { '\ud835', '\udd07' }, { '\u00b4' },
            { '\u02d9' }, { '\u02dd' }, { '\u0060' }, { '\u02dc' },
            { '\u22c4' }, { '\u2146' }, { '\ud835', '\udd3b' }, { '\u00a8' },
            { '\u20dc' }, { '\u2250' }, { '\u222f' }, { '\u00a8' },
            { '\u21d3' }, { '\u21d0' }, { '\u21d4' }, { '\u2ae4' },
            { '\u27f8' }, { '\u27fa' }, { '\u27f9' }, { '\u21d2' },
            { '\u22a8' }, { '\u21d1' }, { '\u21d5' }, { '\u2225' },
            { '\u2193' }, { '\u2913' }, { '\u21f5' }, { '\u0311' },
            { '\u2950' }, { '\u295e' }, { '\u21bd' }, { '\u2956' },
            { '\u295f' }, { '\u21c1' }, { '\u2957' }, { '\u22a4' },
            { '\u21a7' }, { '\u21d3' }, { '\ud835', '\udc9f' }, { '\u0110' },
            { '\u014a' }, { '\u00d0' }, { '\u00d0' }, { '\u00c9' },
            { '\u00c9' }, { '\u011a' }, { '\u00ca' }, { '\u00ca' },
            { '\u042d' }, { '\u0116' }, { '\ud835', '\udd08' }, { '\u00c8' },
            { '\u00c8' }, { '\u2208' }, { '\u0112' }, { '\u25fb' },
            { '\u25ab' }, { '\u0118' }, { '\ud835', '\udd3c' }, { '\u0395' },
            { '\u2a75' }, { '\u2242' }, { '\u21cc' }, { '\u2130' },
            { '\u2a73' }, { '\u0397' }, { '\u00cb' }, { '\u00cb' },
            { '\u2203' }, { '\u2147' }, { '\u0424' }, { '\ud835', '\udd09' },
            { '\u25fc' }, { '\u25aa' }, { '\ud835', '\udd3d' }, { '\u2200' },
            { '\u2131' }, { '\u2131' }, { '\u0403' }, { '\u003e' },
            { '\u003e' }, { '\u0393' }, { '\u03dc' }, { '\u011e' },
            { '\u0122' }, { '\u011c' }, { '\u0413' }, { '\u0120' },
            { '\ud835', '\udd0a' }, { '\u22d9' }, { '\ud835', '\udd3e' },
            { '\u2265' }, { '\u22db' }, { '\u2267' }, { '\u2aa2' },
            { '\u2277' }, { '\u2a7e' }, { '\u2273' }, { '\ud835', '\udca2' },
            { '\u226b' }, { '\u042a' }, { '\u02c7' }, { '\u005e' },
            { '\u0124' }, { '\u210c' }, { '\u210b' }, { '\u210d' },
            { '\u2500' }, { '\u210b' }, { '\u0126' }, { '\u224e' },
            { '\u224f' }, { '\u0415' }, { '\u0132' }, { '\u0401' },
            { '\u00cd' }, { '\u00cd' }, { '\u00ce' }, { '\u00ce' },
            { '\u0418' }, { '\u0130' }, { '\u2111' }, { '\u00cc' },
            { '\u00cc' }, { '\u2111' }, { '\u012a' }, { '\u2148' },
            { '\u21d2' }, { '\u222c' }, { '\u222b' }, { '\u22c2' },
            { '\u2063' }, { '\u2062' }, { '\u012e' }, { '\ud835', '\udd40' },
            { '\u0399' }, { '\u2110' }, { '\u0128' }, { '\u0406' },
            { '\u00cf' }, { '\u00cf' }, { '\u0134' }, { '\u0419' },
            { '\ud835', '\udd0d' }, { '\ud835', '\udd41' },
            { '\ud835', '\udca5' }, { '\u0408' }, { '\u0404' }, { '\u0425' },
            { '\u040c' }, { '\u039a' }, { '\u0136' }, { '\u041a' },
            { '\ud835', '\udd0e' }, { '\ud835', '\udd42' },
            { '\ud835', '\udca6' }, { '\u0409' }, { '\u003c' }, { '\u003c' },
            { '\u0139' }, { '\u039b' }, { '\u27ea' }, { '\u2112' },
            { '\u219e' }, { '\u013d' }, { '\u013b' }, { '\u041b' },
            { '\u27e8' }, { '\u2190' }, { '\u21e4' }, { '\u21c6' },
            { '\u2308' }, { '\u27e6' }, { '\u2961' }, { '\u21c3' },
            { '\u2959' }, { '\u230a' }, { '\u2194' }, { '\u294e' },
            { '\u22a3' }, { '\u21a4' }, { '\u295a' }, { '\u22b2' },
            { '\u29cf' }, { '\u22b4' }, { '\u2951' }, { '\u2960' },
            { '\u21bf' }, { '\u2958' }, { '\u21bc' }, { '\u2952' },
            { '\u21d0' }, { '\u21d4' }, { '\u22da' }, { '\u2266' },
            { '\u2276' }, { '\u2aa1' }, { '\u2a7d' }, { '\u2272' },
            { '\ud835', '\udd0f' }, { '\u22d8' }, { '\u21da' }, { '\u013f' },
            { '\u27f5' }, { '\u27f7' }, { '\u27f6' }, { '\u27f8' },
            { '\u27fa' }, { '\u27f9' }, { '\ud835', '\udd43' }, { '\u2199' },
            { '\u2198' }, { '\u2112' }, { '\u21b0' }, { '\u0141' },
            { '\u226a' }, { '\u2905' }, { '\u041c' }, { '\u205f' },
            { '\u2133' }, { '\ud835', '\udd10' }, { '\u2213' },
            { '\ud835', '\udd44' }, { '\u2133' }, { '\u039c' }, { '\u040a' },
            { '\u0143' }, { '\u0147' }, { '\u0145' }, { '\u041d' },
            { '\u200b' }, { '\u200b' }, { '\u200b' }, { '\u200b' },
            { '\u226b' }, { '\u226a' }, { '\n' }, { '\ud835', '\udd11' },
            { '\u2060' }, { '\u00a0' }, { '\u2115' }, { '\u2aec' },
            { '\u2262' }, { '\u226d' }, { '\u2226' }, { '\u2209' },
            { '\u2260' }, { '\u2204' }, { '\u226f' }, { '\u2271' },
            { '\u2279' }, { '\u2275' }, { '\u22ea' }, { '\u22ec' },
            { '\u226e' }, { '\u2270' }, { '\u2278' }, { '\u2274' },
            { '\u2280' }, { '\u22e0' }, { '\u220c' }, { '\u22eb' },
            { '\u22ed' }, { '\u22e2' }, { '\u22e3' }, { '\u2288' },
            { '\u2281' }, { '\u22e1' }, { '\u2289' }, { '\u2241' },
            { '\u2244' }, { '\u2247' }, { '\u2249' }, { '\u2224' },
            { '\ud835', '\udca9' }, { '\u00d1' }, { '\u00d1' }, { '\u039d' },
            { '\u0152' }, { '\u00d3' }, { '\u00d3' }, { '\u00d4' },
            { '\u00d4' }, { '\u041e' }, { '\u0150' }, { '\ud835', '\udd12' },
            { '\u00d2' }, { '\u00d2' }, { '\u014c' }, { '\u03a9' },
            { '\u039f' }, { '\ud835', '\udd46' }, { '\u201c' }, { '\u2018' },
            { '\u2a54' }, { '\ud835', '\udcaa' }, { '\u00d8' }, { '\u00d8' },
            { '\u00d5' }, { '\u00d5' }, { '\u2a37' }, { '\u00d6' },
            { '\u00d6' }, { '\u203e' }, { '\u23de' }, { '\u23b4' },
            { '\u23dc' }, { '\u2202' }, { '\u041f' }, { '\ud835', '\udd13' },
            { '\u03a6' }, { '\u03a0' }, { '\u00b1' }, { '\u210c' },
            { '\u2119' }, { '\u2abb' }, { '\u227a' }, { '\u2aaf' },
            { '\u227c' }, { '\u227e' }, { '\u2033' }, { '\u220f' },
            { '\u2237' }, { '\u221d' }, { '\ud835', '\udcab' }, { '\u03a8' },
            { '\u0022' }, { '\u0022' }, { '\ud835', '\udd14' }, { '\u211a' },
            { '\ud835', '\udcac' }, { '\u2910' }, { '\u00ae' }, { '\u00ae' },
            { '\u0154' }, { '\u27eb' }, { '\u21a0' }, { '\u2916' },
            { '\u0158' }, { '\u0156' }, { '\u0420' }, { '\u211c' },
            { '\u220b' }, { '\u21cb' }, { '\u296f' }, { '\u211c' },
            { '\u03a1' }, { '\u27e9' }, { '\u2192' }, { '\u21e5' },
            { '\u21c4' }, { '\u2309' }, { '\u27e7' }, { '\u295d' },
            { '\u21c2' }, { '\u2955' }, { '\u230b' }, { '\u22a2' },
            { '\u21a6' }, { '\u295b' }, { '\u22b3' }, { '\u29d0' },
            { '\u22b5' }, { '\u294f' }, { '\u295c' }, { '\u21be' },
            { '\u2954' }, { '\u21c0' }, { '\u2953' }, { '\u21d2' },
            { '\u211d' }, { '\u2970' }, { '\u21db' }, { '\u211b' },
            { '\u21b1' }, { '\u29f4' }, { '\u0429' }, { '\u0428' },
            { '\u042c' }, { '\u015a' }, { '\u2abc' }, { '\u0160' },
            { '\u015e' }, { '\u015c' }, { '\u0421' }, { '\ud835', '\udd16' },
            { '\u2193' }, { '\u2190' }, { '\u2192' }, { '\u2191' },
            { '\u03a3' }, { '\u2218' }, { '\ud835', '\udd4a' }, { '\u221a' },
            { '\u25a1' }, { '\u2293' }, { '\u228f' }, { '\u2291' },
            { '\u2290' }, { '\u2292' }, { '\u2294' }, { '\ud835', '\udcae' },
            { '\u22c6' }, { '\u22d0' }, { '\u22d0' }, { '\u2286' },
            { '\u227b' }, { '\u2ab0' }, { '\u227d' }, { '\u227f' },
            { '\u220b' }, { '\u2211' }, { '\u22d1' }, { '\u2283' },
            { '\u2287' }, { '\u22d1' }, { '\u00de' }, { '\u00de' },
            { '\u2122' }, { '\u040b' }, { '\u0426' }, { '\u0009' },
            { '\u03a4' }, { '\u0164' }, { '\u0162' }, { '\u0422' },
            { '\ud835', '\udd17' }, { '\u2234' }, { '\u0398' }, { '\u2009' },
            { '\u223c' }, { '\u2243' }, { '\u2245' }, { '\u2248' },
            { '\ud835', '\udd4b' }, { '\u20db' }, { '\ud835', '\udcaf' },
            { '\u0166' }, { '\u00da' }, { '\u00da' }, { '\u219f' },
            { '\u2949' }, { '\u040e' }, { '\u016c' }, { '\u00db' },
            { '\u00db' }, { '\u0423' }, { '\u0170' }, { '\ud835', '\udd18' },
            { '\u00d9' }, { '\u00d9' }, { '\u016a' }, { '\u005f' },
            { '\u23df' }, { '\u23b5' }, { '\u23dd' }, { '\u22c3' },
            { '\u228e' }, { '\u0172' }, { '\ud835', '\udd4c' }, { '\u2191' },
            { '\u2912' }, { '\u21c5' }, { '\u2195' }, { '\u296e' },
            { '\u22a5' }, { '\u21a5' }, { '\u21d1' }, { '\u21d5' },
            { '\u2196' }, { '\u2197' }, { '\u03d2' }, { '\u03a5' },
            { '\u016e' }, { '\ud835', '\udcb0' }, { '\u0168' }, { '\u00dc' },
            { '\u00dc' }, { '\u22ab' }, { '\u2aeb' }, { '\u0412' },
            { '\u22a9' }, { '\u2ae6' }, { '\u22c1' }, { '\u2016' },
            { '\u2016' }, { '\u2223' }, { '\u007c' }, { '\u2758' },
            { '\u2240' }, { '\u200a' }, { '\ud835', '\udd19' },
            { '\ud835', '\udd4d' }, { '\ud835', '\udcb1' }, { '\u22aa' },
            { '\u0174' }, { '\u22c0' }, { '\ud835', '\udd1a' },
            { '\ud835', '\udd4e' }, { '\ud835', '\udcb2' },
            { '\ud835', '\udd1b' }, { '\u039e' }, { '\ud835', '\udd4f' },
            { '\ud835', '\udcb3' }, { '\u042f' }, { '\u0407' }, { '\u042e' },
            { '\u00dd' }, { '\u00dd' }, { '\u0176' }, { '\u042b' },
            { '\ud835', '\udd1c' }, { '\ud835', '\udd50' },
            { '\ud835', '\udcb4' }, { '\u0178' }, { '\u0416' }, { '\u0179' },
            { '\u017d' }, { '\u0417' }, { '\u017b' }, { '\u200b' },
            { '\u0396' }, { '\u2128' }, { '\u2124' }, { '\ud835', '\udcb5' },
            { '\u00e1' }, { '\u00e1' }, { '\u0103' }, { '\u223e' },
            { '\u223f' }, { '\u00e2' }, { '\u00e2' }, { '\u00b4' },
            { '\u00b4' }, { '\u0430' }, { '\u00e6' }, { '\u00e6' },
            { '\u2061' }, { '\ud835', '\udd1e' }, { '\u00e0' }, { '\u00e0' },
            { '\u2135' }, { '\u2135' }, { '\u03b1' }, { '\u0101' },
            { '\u2a3f' }, { '\u0026' }, { '\u0026' }, { '\u2227' },
            { '\u2a55' }, { '\u2a5c' }, { '\u2a58' }, { '\u2a5a' },
            { '\u2220' }, { '\u29a4' }, { '\u2220' }, { '\u2221' },
            { '\u29a8' }, { '\u29a9' }, { '\u29aa' }, { '\u29ab' },
            { '\u29ac' }, { '\u29ad' }, { '\u29ae' }, { '\u29af' },
            { '\u221f' }, { '\u22be' }, { '\u299d' }, { '\u2222' },
            { '\u00c5' }, { '\u237c' }, { '\u0105' }, { '\ud835', '\udd52' },
            { '\u2248' }, { '\u2a70' }, { '\u2a6f' }, { '\u224a' },
            { '\u224b' }, { '\'' }, { '\u2248' }, { '\u224a' }, { '\u00e5' },
            { '\u00e5' }, { '\ud835', '\udcb6' }, { '\u002a' }, { '\u2248' },
            { '\u224d' }, { '\u00e3' }, { '\u00e3' }, { '\u00e4' },
            { '\u00e4' }, { '\u2233' }, { '\u2a11' }, { '\u2aed' },
            { '\u224c' }, { '\u03f6' }, { '\u2035' }, { '\u223d' },
            { '\u22cd' }, { '\u22bd' }, { '\u2305' }, { '\u2305' },
            { '\u23b5' }, { '\u23b6' }, { '\u224c' }, { '\u0431' },
            { '\u201e' }, { '\u2235' }, { '\u2235' }, { '\u29b0' },
            { '\u03f6' }, { '\u212c' }, { '\u03b2' }, { '\u2136' },
            { '\u226c' }, { '\ud835', '\udd1f' }, { '\u22c2' }, { '\u25ef' },
            { '\u22c3' }, { '\u2a00' }, { '\u2a01' }, { '\u2a02' },
            { '\u2a06' }, { '\u2605' }, { '\u25bd' }, { '\u25b3' },
            { '\u2a04' }, { '\u22c1' }, { '\u22c0' }, { '\u290d' },
            { '\u29eb' }, { '\u25aa' }, { '\u25b4' }, { '\u25be' },
            { '\u25c2' }, { '\u25b8' }, { '\u2423' }, { '\u2592' },
            { '\u2591' }, { '\u2593' }, { '\u2588' }, { '\u2310' },
            { '\ud835', '\udd53' }, { '\u22a5' }, { '\u22a5' }, { '\u22c8' },
            { '\u2557' }, { '\u2554' }, { '\u2556' }, { '\u2553' },
            { '\u2550' }, { '\u2566' }, { '\u2569' }, { '\u2564' },
            { '\u2567' }, { '\u255d' }, { '\u255a' }, { '\u255c' },
            { '\u2559' }, { '\u2551' }, { '\u256c' }, { '\u2563' },
            { '\u2560' }, { '\u256b' }, { '\u2562' }, { '\u255f' },
            { '\u29c9' }, { '\u2555' }, { '\u2552' }, { '\u2510' },
            { '\u250c' }, { '\u2500' }, { '\u2565' }, { '\u2568' },
            { '\u252c' }, { '\u2534' }, { '\u229f' }, { '\u229e' },
            { '\u22a0' }, { '\u255b' }, { '\u2558' }, { '\u2518' },
            { '\u2514' }, { '\u2502' }, { '\u256a' }, { '\u2561' },
            { '\u255e' }, { '\u253c' }, { '\u2524' }, { '\u251c' },
            { '\u2035' }, { '\u02d8' }, { '\u00a6' }, { '\u00a6' },
            { '\ud835', '\udcb7' }, { '\u204f' }, { '\u223d' }, { '\u22cd' },
            { '\\' }, { '\u29c5' }, { '\u27c8' }, { '\u2022' }, { '\u2022' },
            { '\u224e' }, { '\u2aae' }, { '\u224f' }, { '\u224f' },
            { '\u0107' }, { '\u2229' }, { '\u2a44' }, { '\u2a49' },
            { '\u2a4b' }, { '\u2a47' }, { '\u2a40' }, { '\u2041' },
            { '\u02c7' }, { '\u2a4d' }, { '\u010d' }, { '\u00e7' },
            { '\u00e7' }, { '\u0109' }, { '\u2a4c' }, { '\u2a50' },
            { '\u010b' }, { '\u00b8' }, { '\u00b8' }, { '\u29b2' },
            { '\u00a2' }, { '\u00a2' }, { '\u00b7' }, { '\ud835', '\udd20' },
            { '\u0447' }, { '\u2713' }, { '\u2713' }, { '\u03c7' },
            { '\u25cb' }, { '\u29c3' }, { '\u02c6' }, { '\u2257' },
            { '\u21ba' }, { '\u21bb' }, { '\u00ae' }, { '\u24c8' },
            { '\u229b' }, { '\u229a' }, { '\u229d' }, { '\u2257' },
            { '\u2a10' }, { '\u2aef' }, { '\u29c2' }, { '\u2663' },
            { '\u2663' }, { '\u003a' }, { '\u2254' }, { '\u2254' },
            { '\u002c' }, { '\u0040' }, { '\u2201' }, { '\u2218' },
            { '\u2201' }, { '\u2102' }, { '\u2245' }, { '\u2a6d' },
            { '\u222e' }, { '\ud835', '\udd54' }, { '\u2210' }, { '\u00a9' },
            { '\u00a9' }, { '\u2117' }, { '\u21b5' }, { '\u2717' },
            { '\ud835', '\udcb8' }, { '\u2acf' }, { '\u2ad1' }, { '\u2ad0' },
            { '\u2ad2' }, { '\u22ef' }, { '\u2938' }, { '\u2935' },
            { '\u22de' }, { '\u22df' }, { '\u21b6' }, { '\u293d' },
            { '\u222a' }, { '\u2a48' }, { '\u2a46' }, { '\u2a4a' },
            { '\u228d' }, { '\u2a45' }, { '\u21b7' }, { '\u293c' },
            { '\u22de' }, { '\u22df' }, { '\u22ce' }, { '\u22cf' },
            { '\u00a4' }, { '\u00a4' }, { '\u21b6' }, { '\u21b7' },
            { '\u22ce' }, { '\u22cf' }, { '\u2232' }, { '\u2231' },
            { '\u232d' }, { '\u21d3' }, { '\u2965' }, { '\u2020' },
            { '\u2138' }, { '\u2193' }, { '\u2010' }, { '\u22a3' },
            { '\u290f' }, { '\u02dd' }, { '\u010f' }, { '\u0434' },
            { '\u2146' }, { '\u2021' }, { '\u21ca' }, { '\u2a77' },
            { '\u00b0' }, { '\u00b0' }, { '\u03b4' }, { '\u29b1' },
            { '\u297f' }, { '\ud835', '\udd21' }, { '\u21c3' }, { '\u21c2' },
            { '\u22c4' }, { '\u22c4' }, { '\u2666' }, { '\u2666' },
            { '\u00a8' }, { '\u03dd' }, { '\u22f2' }, { '\u00f7' },
            { '\u00f7' }, { '\u00f7' }, { '\u22c7' }, { '\u22c7' },
            { '\u0452' }, { '\u231e' }, { '\u230d' }, { '\u0024' },
            { '\ud835', '\udd55' }, { '\u02d9' }, { '\u2250' }, { '\u2251' },
            { '\u2238' }, { '\u2214' }, { '\u22a1' }, { '\u2306' },
            { '\u2193' }, { '\u21ca' }, { '\u21c3' }, { '\u21c2' },
            { '\u2910' }, { '\u231f' }, { '\u230c' }, { '\ud835', '\udcb9' },
            { '\u0455' }, { '\u29f6' }, { '\u0111' }, { '\u22f1' },
            { '\u25bf' }, { '\u25be' }, { '\u21f5' }, { '\u296f' },
            { '\u29a6' }, { '\u045f' }, { '\u27ff' }, { '\u2a77' },
            { '\u2251' }, { '\u00e9' }, { '\u00e9' }, { '\u2a6e' },
            { '\u011b' }, { '\u2256' }, { '\u00ea' }, { '\u00ea' },
            { '\u2255' }, { '\u044d' }, { '\u0117' }, { '\u2147' },
            { '\u2252' }, { '\ud835', '\udd22' }, { '\u2a9a' }, { '\u00e8' },
            { '\u00e8' }, { '\u2a96' }, { '\u2a98' }, { '\u2a99' },
            { '\u23e7' }, { '\u2113' }, { '\u2a95' }, { '\u2a97' },
            { '\u0113' }, { '\u2205' }, { '\u2205' }, { '\u2205' },
            { '\u2004' }, { '\u2005' }, { '\u2003' }, { '\u014b' },
            { '\u2002' }, { '\u0119' }, { '\ud835', '\udd56' }, { '\u22d5' },
            { '\u29e3' }, { '\u2a71' }, { '\u03b5' }, { '\u03b5' },
            { '\u03f5' }, { '\u2256' }, { '\u2255' }, { '\u2242' },
            { '\u2a96' }, { '\u2a95' }, { '\u003d' }, { '\u225f' },
            { '\u2261' }, { '\u2a78' }, { '\u29e5' }, { '\u2253' },
            { '\u2971' }, { '\u212f' }, { '\u2250' }, { '\u2242' },
            { '\u03b7' }, { '\u00f0' }, { '\u00f0' }, { '\u00eb' },
            { '\u00eb' }, { '\u20ac' }, { '\u0021' }, { '\u2203' },
            { '\u2130' }, { '\u2147' }, { '\u2252' }, { '\u0444' },
            { '\u2640' }, { '\ufb03' }, { '\ufb00' }, { '\ufb04' },
            { '\ud835', '\udd23' }, { '\ufb01' }, { '\u266d' }, { '\ufb02' },
            { '\u25b1' }, { '\u0192' }, { '\ud835', '\udd57' }, { '\u2200' },
            { '\u22d4' }, { '\u2ad9' }, { '\u2a0d' }, { '\u00bd' },
            { '\u00bd' }, { '\u2153' }, { '\u00bc' }, { '\u00bc' },
            { '\u2155' }, { '\u2159' }, { '\u215b' }, { '\u2154' },
            { '\u2156' }, { '\u00be' }, { '\u00be' }, { '\u2157' },
            { '\u215c' }, { '\u2158' }, { '\u215a' }, { '\u215d' },
            { '\u215e' }, { '\u2044' }, { '\u2322' }, { '\ud835', '\udcbb' },
            { '\u2267' }, { '\u2a8c' }, { '\u01f5' }, { '\u03b3' },
            { '\u03dd' }, { '\u2a86' }, { '\u011f' }, { '\u011d' },
            { '\u0433' }, { '\u0121' }, { '\u2265' }, { '\u22db' },
            { '\u2265' }, { '\u2267' }, { '\u2a7e' }, { '\u2a7e' },
            { '\u2aa9' }, { '\u2a80' }, { '\u2a82' }, { '\u2a84' },
            { '\u2a94' }, { '\ud835', '\udd24' }, { '\u226b' }, { '\u22d9' },
            { '\u2137' }, { '\u0453' }, { '\u2277' }, { '\u2a92' },
            { '\u2aa5' }, { '\u2aa4' }, { '\u2269' }, { '\u2a8a' },
            { '\u2a8a' }, { '\u2a88' }, { '\u2a88' }, { '\u2269' },
            { '\u22e7' }, { '\ud835', '\udd58' }, { '\u0060' }, { '\u210a' },
            { '\u2273' }, { '\u2a8e' }, { '\u2a90' }, { '\u003e' },
            { '\u003e' }, { '\u2aa7' }, { '\u2a7a' }, { '\u22d7' },
            { '\u2995' }, { '\u2a7c' }, { '\u2a86' }, { '\u2978' },
            { '\u22d7' }, { '\u22db' }, { '\u2a8c' }, { '\u2277' },
            { '\u2273' }, { '\u21d4' }, { '\u200a' }, { '\u00bd' },
            { '\u210b' }, { '\u044a' }, { '\u2194' }, { '\u2948' },
            { '\u21ad' }, { '\u210f' }, { '\u0125' }, { '\u2665' },
            { '\u2665' }, { '\u2026' }, { '\u22b9' }, { '\ud835', '\udd25' },
            { '\u2925' }, { '\u2926' }, { '\u21ff' }, { '\u223b' },
            { '\u21a9' }, { '\u21aa' }, { '\ud835', '\udd59' }, { '\u2015' },
            { '\ud835', '\udcbd' }, { '\u210f' }, { '\u0127' }, { '\u2043' },
            { '\u2010' }, { '\u00ed' }, { '\u00ed' }, { '\u2063' },
            { '\u00ee' }, { '\u00ee' }, { '\u0438' }, { '\u0435' },
            { '\u00a1' }, { '\u00a1' }, { '\u21d4' }, { '\ud835', '\udd26' },
            { '\u00ec' }, { '\u00ec' }, { '\u2148' }, { '\u2a0c' },
            { '\u222d' }, { '\u29dc' }, { '\u2129' }, { '\u0133' },
            { '\u012b' }, { '\u2111' }, { '\u2110' }, { '\u2111' },
            { '\u0131' }, { '\u22b7' }, { '\u01b5' }, { '\u2208' },
            { '\u2105' }, { '\u221e' }, { '\u29dd' }, { '\u0131' },
            { '\u222b' }, { '\u22ba' }, { '\u2124' }, { '\u22ba' },
            { '\u2a17' }, { '\u2a3c' }, { '\u0451' }, { '\u012f' },
            { '\ud835', '\udd5a' }, { '\u03b9' }, { '\u2a3c' }, { '\u00bf' },
            { '\u00bf' }, { '\ud835', '\udcbe' }, { '\u2208' }, { '\u22f9' },
            { '\u22f5' }, { '\u22f4' }, { '\u22f3' }, { '\u2208' },
            { '\u2062' }, { '\u0129' }, { '\u0456' }, { '\u00ef' },
            { '\u00ef' }, { '\u0135' }, { '\u0439' }, { '\ud835', '\udd27' },
            { '\u0237' }, { '\ud835', '\udd5b' }, { '\ud835', '\udcbf' },
            { '\u0458' }, { '\u0454' }, { '\u03ba' }, { '\u03f0' },
            { '\u0137' }, { '\u043a' }, { '\ud835', '\udd28' }, { '\u0138' },
            { '\u0445' }, { '\u045c' }, { '\ud835', '\udd5c' },
            { '\ud835', '\udcc0' }, { '\u21da' }, { '\u21d0' }, { '\u291b' },
            { '\u290e' }, { '\u2266' }, { '\u2a8b' }, { '\u2962' },
            { '\u013a' }, { '\u29b4' }, { '\u2112' }, { '\u03bb' },
            { '\u27e8' }, { '\u2991' }, { '\u27e8' }, { '\u2a85' },
            { '\u00ab' }, { '\u00ab' }, { '\u2190' }, { '\u21e4' },
            { '\u291f' }, { '\u291d' }, { '\u21a9' }, { '\u21ab' },
            { '\u2939' }, { '\u2973' }, { '\u21a2' }, { '\u2aab' },
            { '\u2919' }, { '\u2aad' }, { '\u290c' }, { '\u2772' },
            { '\u007b' }, { '\u005b' }, { '\u298b' }, { '\u298f' },
            { '\u298d' }, { '\u013e' }, { '\u013c' }, { '\u2308' },
            { '\u007b' }, { '\u043b' }, { '\u2936' }, { '\u201c' },
            { '\u201e' }, { '\u2967' }, { '\u294b' }, { '\u21b2' },
            { '\u2264' }, { '\u2190' }, { '\u21a2' }, { '\u21bd' },
            { '\u21bc' }, { '\u21c7' }, { '\u2194' }, { '\u21c6' },
            { '\u21cb' }, { '\u21ad' }, { '\u22cb' }, { '\u22da' },
            { '\u2264' }, { '\u2266' }, { '\u2a7d' }, { '\u2a7d' },
            { '\u2aa8' }, { '\u2a7f' }, { '\u2a81' }, { '\u2a83' },
            { '\u2a93' }, { '\u2a85' }, { '\u22d6' }, { '\u22da' },
            { '\u2a8b' }, { '\u2276' }, { '\u2272' }, { '\u297c' },
            { '\u230a' }, { '\ud835', '\udd29' }, { '\u2276' }, { '\u2a91' },
            { '\u21bd' }, { '\u21bc' }, { '\u296a' }, { '\u2584' },
            { '\u0459' }, { '\u226a' }, { '\u21c7' }, { '\u231e' },
            { '\u296b' }, { '\u25fa' }, { '\u0140' }, { '\u23b0' },
            { '\u23b0' }, { '\u2268' }, { '\u2a89' }, { '\u2a89' },
            { '\u2a87' }, { '\u2a87' }, { '\u2268' }, { '\u22e6' },
            { '\u27ec' }, { '\u21fd' }, { '\u27e6' }, { '\u27f5' },
            { '\u27f7' }, { '\u27fc' }, { '\u27f6' }, { '\u21ab' },
            { '\u21ac' }, { '\u2985' }, { '\ud835', '\udd5d' }, { '\u2a2d' },
            { '\u2a34' }, { '\u2217' }, { '\u005f' }, { '\u25ca' },
            { '\u25ca' }, { '\u29eb' }, { '\u0028' }, { '\u2993' },
            { '\u21c6' }, { '\u231f' }, { '\u21cb' }, { '\u296d' },
            { '\u200e' }, { '\u22bf' }, { '\u2039' }, { '\ud835', '\udcc1' },
            { '\u21b0' }, { '\u2272' }, { '\u2a8d' }, { '\u2a8f' },
            { '\u005b' }, { '\u2018' }, { '\u201a' }, { '\u0142' },
            { '\u003c' }, { '\u003c' }, { '\u2aa6' }, { '\u2a79' },
            { '\u22d6' }, { '\u22cb' }, { '\u22c9' }, { '\u2976' },
            { '\u2a7b' }, { '\u2996' }, { '\u25c3' }, { '\u22b4' },
            { '\u25c2' }, { '\u294a' }, { '\u2966' }, { '\u223a' },
            { '\u00af' }, { '\u00af' }, { '\u2642' }, { '\u2720' },
            { '\u2720' }, { '\u21a6' }, { '\u21a6' }, { '\u21a7' },
            { '\u21a4' }, { '\u21a5' }, { '\u25ae' }, { '\u2a29' },
            { '\u043c' }, { '\u2014' }, { '\u2221' }, { '\ud835', '\udd2a' },
            { '\u2127' }, { '\u00b5' }, { '\u00b5' }, { '\u2223' },
            { '\u002a' }, { '\u2af0' }, { '\u00b7' }, { '\u00b7' },
            { '\u2212' }, { '\u229f' }, { '\u2238' }, { '\u2a2a' },
            { '\u2adb' }, { '\u2026' }, { '\u2213' }, { '\u22a7' },
            { '\ud835', '\udd5e' }, { '\u2213' }, { '\ud835', '\udcc2' },
            { '\u223e' }, { '\u03bc' }, { '\u22b8' }, { '\u22b8' },
            { '\u21cd' }, { '\u21ce' }, { '\u21cf' }, { '\u22af' },
            { '\u22ae' }, { '\u2207' }, { '\u0144' }, { '\u2249' },
            { '\u0149' }, { '\u2249' }, { '\u266e' }, { '\u266e' },
            { '\u2115' }, { '\u00a0' }, { '\u00a0' }, { '\u2a43' },
            { '\u0148' }, { '\u0146' }, { '\u2247' }, { '\u2a42' },
            { '\u043d' }, { '\u2013' }, { '\u2260' }, { '\u21d7' },
            { '\u2924' }, { '\u2197' }, { '\u2197' }, { '\u2262' },
            { '\u2928' }, { '\u2204' }, { '\u2204' }, { '\ud835', '\udd2b' },
            { '\u2271' }, { '\u2271' }, { '\u2275' }, { '\u226f' },
            { '\u226f' }, { '\u21ce' }, { '\u21ae' }, { '\u2af2' },
            { '\u220b' }, { '\u22fc' }, { '\u22fa' }, { '\u220b' },
            { '\u045a' }, { '\u21cd' }, { '\u219a' }, { '\u2025' },
            { '\u2270' }, { '\u219a' }, { '\u21ae' }, { '\u2270' },
            { '\u226e' }, { '\u2274' }, { '\u226e' }, { '\u22ea' },
            { '\u22ec' }, { '\u2224' }, { '\ud835', '\udd5f' }, { '\u00ac' },
            { '\u00ac' }, { '\u2209' }, { '\u2209' }, { '\u22f7' },
            { '\u22f6' }, { '\u220c' }, { '\u220c' }, { '\u22fe' },
            { '\u22fd' }, { '\u2226' }, { '\u2226' }, { '\u2a14' },
            { '\u2280' }, { '\u22e0' }, { '\u2280' }, { '\u21cf' },
            { '\u219b' }, { '\u219b' }, { '\u22eb' }, { '\u22ed' },
            { '\u2281' }, { '\u22e1' }, { '\ud835', '\udcc3' }, { '\u2224' },
            { '\u2226' }, { '\u2241' }, { '\u2244' }, { '\u2244' },
            { '\u2224' }, { '\u2226' }, { '\u22e2' }, { '\u22e3' },
            { '\u2284' }, { '\u2288' }, { '\u2288' }, { '\u2281' },
            { '\u2285' }, { '\u2289' }, { '\u2289' }, { '\u2279' },
            { '\u00f1' }, { '\u00f1' }, { '\u2278' }, { '\u22ea' },
            { '\u22ec' }, { '\u22eb' }, { '\u22ed' }, { '\u03bd' },
            { '\u0023' }, { '\u2116' }, { '\u2007' }, { '\u22ad' },
            { '\u2904' }, { '\u22ac' }, { '\u29de' }, { '\u2902' },
            { '\u2903' }, { '\u21d6' }, { '\u2923' }, { '\u2196' },
            { '\u2196' }, { '\u2927' }, { '\u24c8' }, { '\u00f3' },
            { '\u00f3' }, { '\u229b' }, { '\u229a' }, { '\u00f4' },
            { '\u00f4' }, { '\u043e' }, { '\u229d' }, { '\u0151' },
            { '\u2a38' }, { '\u2299' }, { '\u29bc' }, { '\u0153' },
            { '\u29bf' }, { '\ud835', '\udd2c' }, { '\u02db' }, { '\u00f2' },
            { '\u00f2' }, { '\u29c1' }, { '\u29b5' }, { '\u03a9' },
            { '\u222e' }, { '\u21ba' }, { '\u29be' }, { '\u29bb' },
            { '\u203e' }, { '\u29c0' }, { '\u014d' }, { '\u03c9' },
            { '\u03bf' }, { '\u29b6' }, { '\u2296' }, { '\ud835', '\udd60' },
            { '\u29b7' }, { '\u29b9' }, { '\u2295' }, { '\u2228' },
            { '\u21bb' }, { '\u2a5d' }, { '\u2134' }, { '\u2134' },
            { '\u00aa' }, { '\u00aa' }, { '\u00ba' }, { '\u00ba' },
            { '\u22b6' }, { '\u2a56' }, { '\u2a57' }, { '\u2a5b' },
            { '\u2134' }, { '\u00f8' }, { '\u00f8' }, { '\u2298' },
            { '\u00f5' }, { '\u00f5' }, { '\u2297' }, { '\u2a36' },
            { '\u00f6' }, { '\u00f6' }, { '\u233d' }, { '\u2225' },
            { '\u00b6' }, { '\u00b6' }, { '\u2225' }, { '\u2af3' },
            { '\u2afd' }, { '\u2202' }, { '\u043f' }, { '\u0025' },
            { '\u002e' }, { '\u2030' }, { '\u22a5' }, { '\u2031' },
            { '\ud835', '\udd2d' }, { '\u03c6' }, { '\u03d5' }, { '\u2133' },
            { '\u260e' }, { '\u03c0' }, { '\u22d4' }, { '\u03d6' },
            { '\u210f' }, { '\u210e' }, { '\u210f' }, { '\u002b' },
            { '\u2a23' }, { '\u229e' }, { '\u2a22' }, { '\u2214' },
            { '\u2a25' }, { '\u2a72' }, { '\u00b1' }, { '\u00b1' },
            { '\u2a26' }, { '\u2a27' }, { '\u00b1' }, { '\u2a15' },
            { '\ud835', '\udd61' }, { '\u00a3' }, { '\u00a3' }, { '\u227a' },
            { '\u2ab3' }, { '\u2ab7' }, { '\u227c' }, { '\u2aaf' },
            { '\u227a' }, { '\u2ab7' }, { '\u227c' }, { '\u2aaf' },
            { '\u2ab9' }, { '\u2ab5' }, { '\u22e8' }, { '\u227e' },
            { '\u2032' }, { '\u2119' }, { '\u2ab5' }, { '\u2ab9' },
            { '\u22e8' }, { '\u220f' }, { '\u232e' }, { '\u2312' },
            { '\u2313' }, { '\u221d' }, { '\u221d' }, { '\u227e' },
            { '\u22b0' }, { '\ud835', '\udcc5' }, { '\u03c8' }, { '\u2008' },
            { '\ud835', '\udd2e' }, { '\u2a0c' }, { '\ud835', '\udd62' },
            { '\u2057' }, { '\ud835', '\udcc6' }, { '\u210d' }, { '\u2a16' },
            { '\u003f' }, { '\u225f' }, { '\u0022' }, { '\u0022' },
            { '\u21db' }, { '\u21d2' }, { '\u291c' }, { '\u290f' },
            { '\u2964' }, { '\u0155' }, { '\u221a' }, { '\u29b3' },
            { '\u27e9' }, { '\u2992' }, { '\u29a5' }, { '\u27e9' },
            { '\u00bb' }, { '\u00bb' }, { '\u2192' }, { '\u2975' },
            { '\u21e5' }, { '\u2920' }, { '\u2933' }, { '\u291e' },
            { '\u21aa' }, { '\u21ac' }, { '\u2945' }, { '\u2974' },
            { '\u21a3' }, { '\u219d' }, { '\u291a' }, { '\u2236' },
            { '\u211a' }, { '\u290d' }, { '\u2773' }, { '\u007d' },
            { '\u005d' }, { '\u298c' }, { '\u298e' }, { '\u2990' },
            { '\u0159' }, { '\u0157' }, { '\u2309' }, { '\u007d' },
            { '\u0440' }, { '\u2937' }, { '\u2969' }, { '\u201d' },
            { '\u201d' }, { '\u21b3' }, { '\u211c' }, { '\u211b' },
            { '\u211c' }, { '\u211d' }, { '\u25ad' }, { '\u00ae' },
            { '\u00ae' }, { '\u297d' }, { '\u230b' }, { '\ud835', '\udd2f' },
            { '\u21c1' }, { '\u21c0' }, { '\u296c' }, { '\u03c1' },
            { '\u03f1' }, { '\u2192' }, { '\u21a3' }, { '\u21c1' },
            { '\u21c0' }, { '\u21c4' }, { '\u21cc' }, { '\u21c9' },
            { '\u219d' }, { '\u22cc' }, { '\u02da' }, { '\u2253' },
            { '\u21c4' }, { '\u21cc' }, { '\u200f' }, { '\u23b1' },
            { '\u23b1' }, { '\u2aee' }, { '\u27ed' }, { '\u21fe' },
            { '\u27e7' }, { '\u2986' }, { '\ud835', '\udd63' }, { '\u2a2e' },
            { '\u2a35' }, { '\u0029' }, { '\u2994' }, { '\u2a12' },
            { '\u21c9' }, { '\u203a' }, { '\ud835', '\udcc7' }, { '\u21b1' },
            { '\u005d' }, { '\u2019' }, { '\u2019' }, { '\u22cc' },
            { '\u22ca' }, { '\u25b9' }, { '\u22b5' }, { '\u25b8' },
            { '\u29ce' }, { '\u2968' }, { '\u211e' }, { '\u015b' },
            { '\u201a' }, { '\u227b' }, { '\u2ab4' }, { '\u2ab8' },
            { '\u0161' }, { '\u227d' }, { '\u2ab0' }, { '\u015f' },
            { '\u015d' }, { '\u2ab6' }, { '\u2aba' }, { '\u22e9' },
            { '\u2a13' }, { '\u227f' }, { '\u0441' }, { '\u22c5' },
            { '\u22a1' }, { '\u2a66' }, { '\u21d8' }, { '\u2925' },
            { '\u2198' }, { '\u2198' }, { '\u00a7' }, { '\u00a7' },
            { '\u003b' }, { '\u2929' }, { '\u2216' }, { '\u2216' },
            { '\u2736' }, { '\ud835', '\udd30' }, { '\u2322' }, { '\u266f' },
            { '\u0449' }, { '\u0448' }, { '\u2223' }, { '\u2225' },
            { '\u00ad' }, { '\u00ad' }, { '\u03c3' }, { '\u03c2' },
            { '\u03c2' }, { '\u223c' }, { '\u2a6a' }, { '\u2243' },
            { '\u2243' }, { '\u2a9e' }, { '\u2aa0' }, { '\u2a9d' },
            { '\u2a9f' }, { '\u2246' }, { '\u2a24' }, { '\u2972' },
            { '\u2190' }, { '\u2216' }, { '\u2a33' }, { '\u29e4' },
            { '\u2223' }, { '\u2323' }, { '\u2aaa' }, { '\u2aac' },
            { '\u044c' }, { '\u002f' }, { '\u29c4' }, { '\u233f' },
            { '\ud835', '\udd64' }, { '\u2660' }, { '\u2660' }, { '\u2225' },
            { '\u2293' }, { '\u2294' }, { '\u228f' }, { '\u2291' },
            { '\u228f' }, { '\u2291' }, { '\u2290' }, { '\u2292' },
            { '\u2290' }, { '\u2292' }, { '\u25a1' }, { '\u25a1' },
            { '\u25aa' }, { '\u25aa' }, { '\u2192' }, { '\ud835', '\udcc8' },
            { '\u2216' }, { '\u2323' }, { '\u22c6' }, { '\u2606' },
            { '\u2605' }, { '\u03f5' }, { '\u03d5' }, { '\u00af' },
            { '\u2282' }, { '\u2ac5' }, { '\u2abd' }, { '\u2286' },
            { '\u2ac3' }, { '\u2ac1' }, { '\u2acb' }, { '\u228a' },
            { '\u2abf' }, { '\u2979' }, { '\u2282' }, { '\u2286' },
            { '\u2ac5' }, { '\u228a' }, { '\u2acb' }, { '\u2ac7' },
            { '\u2ad5' }, { '\u2ad3' }, { '\u227b' }, { '\u2ab8' },
            { '\u227d' }, { '\u2ab0' }, { '\u2aba' }, { '\u2ab6' },
            { '\u22e9' }, { '\u227f' }, { '\u2211' }, { '\u266a' },
            { '\u00b9' }, { '\u00b9' }, { '\u00b2' }, { '\u00b2' },
            { '\u00b3' }, { '\u00b3' }, { '\u2283' }, { '\u2ac6' },
            { '\u2abe' }, { '\u2ad8' }, { '\u2287' }, { '\u2ac4' },
            { '\u27c9' }, { '\u2ad7' }, { '\u297b' }, { '\u2ac2' },
            { '\u2acc' }, { '\u228b' }, { '\u2ac0' }, { '\u2283' },
            { '\u2287' }, { '\u2ac6' }, { '\u228b' }, { '\u2acc' },
            { '\u2ac8' }, { '\u2ad4' }, { '\u2ad6' }, { '\u21d9' },
            { '\u2926' }, { '\u2199' }, { '\u2199' }, { '\u292a' },
            { '\u00df' }, { '\u00df' }, { '\u2316' }, { '\u03c4' },
            { '\u23b4' }, { '\u0165' }, { '\u0163' }, { '\u0442' },
            { '\u20db' }, { '\u2315' }, { '\ud835', '\udd31' }, { '\u2234' },
            { '\u2234' }, { '\u03b8' }, { '\u03d1' }, { '\u03d1' },
            { '\u2248' }, { '\u223c' }, { '\u2009' }, { '\u2248' },
            { '\u223c' }, { '\u00fe' }, { '\u00fe' }, { '\u02dc' },
            { '\u00d7' }, { '\u00d7' }, { '\u22a0' }, { '\u2a31' },
            { '\u2a30' }, { '\u222d' }, { '\u2928' }, { '\u22a4' },
            { '\u2336' }, { '\u2af1' }, { '\ud835', '\udd65' }, { '\u2ada' },
            { '\u2929' }, { '\u2034' }, { '\u2122' }, { '\u25b5' },
            { '\u25bf' }, { '\u25c3' }, { '\u22b4' }, { '\u225c' },
            { '\u25b9' }, { '\u22b5' }, { '\u25ec' }, { '\u225c' },
            { '\u2a3a' }, { '\u2a39' }, { '\u29cd' }, { '\u2a3b' },
            { '\u23e2' }, { '\ud835', '\udcc9' }, { '\u0446' }, { '\u045b' },
            { '\u0167' }, { '\u226c' }, { '\u219e' }, { '\u21a0' },
            { '\u21d1' }, { '\u2963' }, { '\u00fa' }, { '\u00fa' },
            { '\u2191' }, { '\u045e' }, { '\u016d' }, { '\u00fb' },
            { '\u00fb' }, { '\u0443' }, { '\u21c5' }, { '\u0171' },
            { '\u296e' }, { '\u297e' }, { '\ud835', '\udd32' }, { '\u00f9' },
            { '\u00f9' }, { '\u21bf' }, { '\u21be' }, { '\u2580' },
            { '\u231c' }, { '\u231c' }, { '\u230f' }, { '\u25f8' },
            { '\u016b' }, { '\u00a8' }, { '\u00a8' }, { '\u0173' },
            { '\ud835', '\udd66' }, { '\u2191' }, { '\u2195' }, { '\u21bf' },
            { '\u21be' }, { '\u228e' }, { '\u03c5' }, { '\u03d2' },
            { '\u03c5' }, { '\u21c8' }, { '\u231d' }, { '\u231d' },
            { '\u230e' }, { '\u016f' }, { '\u25f9' }, { '\ud835', '\udcca' },
            { '\u22f0' }, { '\u0169' }, { '\u25b5' }, { '\u25b4' },
            { '\u21c8' }, { '\u00fc' }, { '\u00fc' }, { '\u29a7' },
            { '\u21d5' }, { '\u2ae8' }, { '\u2ae9' }, { '\u22a8' },
            { '\u299c' }, { '\u03f5' }, { '\u03f0' }, { '\u2205' },
            { '\u03d5' }, { '\u03d6' }, { '\u221d' }, { '\u2195' },
            { '\u03f1' }, { '\u03c2' }, { '\u03d1' }, { '\u22b2' },
            { '\u22b3' }, { '\u0432' }, { '\u22a2' }, { '\u2228' },
            { '\u22bb' }, { '\u225a' }, { '\u22ee' }, { '\u007c' },
            { '\u007c' }, { '\ud835', '\udd33' }, { '\u22b2' },
            { '\ud835', '\udd67' }, { '\u221d' }, { '\u22b3' },
            { '\ud835', '\udccb' }, { '\u299a' }, { '\u0175' }, { '\u2a5f' },
            { '\u2227' }, { '\u2259' }, { '\u2118' }, { '\ud835', '\udd34' },
            { '\ud835', '\udd68' }, { '\u2118' }, { '\u2240' }, { '\u2240' },
            { '\ud835', '\udccc' }, { '\u22c2' }, { '\u25ef' }, { '\u22c3' },
            { '\u25bd' }, { '\ud835', '\udd35' }, { '\u27fa' }, { '\u27f7' },
            { '\u03be' }, { '\u27f8' }, { '\u27f5' }, { '\u27fc' },
            { '\u22fb' }, { '\u2a00' }, { '\ud835', '\udd69' }, { '\u2a01' },
            { '\u2a02' }, { '\u27f9' }, { '\u27f6' }, { '\ud835', '\udccd' },
            { '\u2a06' }, { '\u2a04' }, { '\u25b3' }, { '\u22c1' },
            { '\u22c0' }, { '\u00fd' }, { '\u00fd' }, { '\u044f' },
            { '\u0177' }, { '\u044b' }, { '\u00a5' }, { '\u00a5' },
            { '\ud835', '\udd36' }, { '\u0457' }, { '\ud835', '\udd6a' },
            { '\ud835', '\udcce' }, { '\u044e' }, { '\u00ff' }, { '\u00ff' },
            { '\u017a' }, { '\u017e' }, { '\u0437' }, { '\u017c' },
            { '\u2128' }, { '\u03b6' }, { '\ud835', '\udd37' }, { '\u0436' },
            { '\u21dd' }, { '\ud835', '\udd6b' }, { '\ud835', '\udccf' },
            { '\u200d' }, { '\u200c' }, };

    final static char[][] WINDOWS_1252 = { { '\u20AC' }, { '\u0081' },
            { '\u201A' }, { '\u0192' }, { '\u201E' }, { '\u2026' },
            { '\u2020' }, { '\u2021' }, { '\u02C6' }, { '\u2030' },
            { '\u0160' }, { '\u2039' }, { '\u0152' }, { '\u008D' },
            { '\u017D' }, { '\u008F' }, { '\u0090' }, { '\u2018' },
            { '\u2019' }, { '\u201C' }, { '\u201D' }, { '\u2022' },
            { '\u2013' }, { '\u2014' }, { '\u02DC' }, { '\u2122' },
            { '\u0161' }, { '\u203A' }, { '\u0153' }, { '\u009D' },
            { '\u017E' }, { '\u0178' } };

}
